/*
 jQuery JavaScript Library v1.9.1
 http://jquery.com/

 Includes Sizzle.js
 http://sizzlejs.com/

 Copyright 2005, 2012 jQuery Foundation, Inc. and other contributors
 Released under the MIT license
 http://jquery.org/license

 Date: 2013-2-4
 Sizzle CSS Selector Engine
 Copyright 2012 jQuery Foundation and other contributors
 Released under the MIT license
 http://sizzlejs.com/
*/
(function(F,y){function eb(a){var b=a.length,d=c.type(a);return c.isWindow(a)?!1:1===a.nodeType&&b?!0:"array"===d||"function"!==d&&(0===b||"number"===typeof b&&0<b&&b-1 in a)}function Bc(a){var b=Db[a]={};c.each(a.match(sa)||[],function(d,e){b[e]=!0});return b}function Eb(a,b,d,e){if(c.acceptData(a)){var f=c.expando,g="string"===typeof b,k=a.nodeType,m=k?c.cache:a,p=k?a[f]:a[f]&&f;if(p&&m[p]&&(e||m[p].data)||!g||d!==y){p||(k?a[f]=p=Da.pop()||c.guid++:p=f);m[p]||(m[p]={},k||(m[p].toJSON=c.noop));if("object"===
	typeof b||"function"===typeof b)e?m[p]=c.extend(m[p],b):m[p].data=c.extend(m[p].data,b);a=m[p];e||(a.data||(a.data={}),a=a.data);d!==y&&(a[c.camelCase(b)]=d);g?(d=a[b],null==d&&(d=a[c.camelCase(b)])):d=a;return d}}}function Fb(a,b,d){if(c.acceptData(a)){var e,f,g=a.nodeType,k=g?c.cache:a,m=g?a[c.expando]:c.expando;if(k[m]){if(b&&(f=d?k[m]:k[m].data)){c.isArray(b)?b=b.concat(c.map(b,c.camelCase)):b in f?b=[b]:(b=c.camelCase(b),b=b in f?[b]:b.split(" "));var p=0;for(e=b.length;p<e;p++)delete f[b[p]];
	if(!(d?fb:c.isEmptyObject)(f))return}if(!d&&(delete k[m].data,!fb(k[m])))return;g?c.cleanData([a],!0):c.support.deleteExpando||k!=k.window?delete k[m]:k[m]=null}}}function Gb(a,b,d){if(d===y&&1===a.nodeType)if(d="data-"+b.replace(Cc,"-$1").toLowerCase(),d=a.getAttribute(d),"string"===typeof d){try{d="true"===d?!0:"false"===d?!1:"null"===d?null:+d+""===d?+d:Dc.test(d)?c.parseJSON(d):d}catch(e){}c.data(a,b,d)}else d=y;return d}function fb(a){for(var b in a)if(("data"!==b||!c.isEmptyObject(a[b]))&&"toJSON"!==
	b)return!1;return!0}function Ta(){return!0}function Ea(){return!1}function Hb(a,b){do a=a[b];while(a&&1!==a.nodeType);return a}function Ib(a,b,d){b=b||0;if(c.isFunction(b))return c.grep(a,function(f,g){return!!b.call(f,g,f)===d});if(b.nodeType)return c.grep(a,function(f){return f===b===d});if("string"===typeof b){var e=c.grep(a,function(f){return 1===f.nodeType});if(Ec.test(b))return c.filter(b,e,!d);b=c.filter(b,e)}return c.grep(a,function(f){return 0<=c.inArray(f,b)===d})}function Jb(a){var b=Kb.split("|");
	a=a.createDocumentFragment();if(a.createElement)for(;b.length;)a.createElement(b.pop());return a}function Fc(a,b){return a.getElementsByTagName(b)[0]||a.appendChild(a.ownerDocument.createElement(b))}function Lb(a){var b=a.getAttributeNode("type");a.type=(b&&b.specified)+"/"+a.type;return a}function Mb(a){var b=Gc.exec(a.type);b?a.type=b[1]:a.removeAttribute("type");return a}function gb(a,b){for(var d,e=0;null!=(d=a[e]);e++)c._data(d,"globalEval",!b||c._data(b[e],"globalEval"))}function Nb(a,b){if(1===
	b.nodeType&&c.hasData(a)){var d,e;var f=c._data(a);a=c._data(b,f);var g=f.events;if(g)for(d in delete a.handle,a.events={},g)for(f=0,e=g[d].length;f<e;f++)c.event.add(b,d,g[d][f]);a.data&&(a.data=c.extend({},a.data))}}function ca(a,b){var d,e,f=0,g=typeof a.getElementsByTagName!==qa?a.getElementsByTagName(b||"*"):typeof a.querySelectorAll!==qa?a.querySelectorAll(b||"*"):y;if(!g)for(g=[],d=a.childNodes||a;null!=(e=d[f]);f++)!b||c.nodeName(e,b)?g.push(e):c.merge(g,ca(e,b));return b===y||b&&c.nodeName(a,
	b)?c.merge([a],g):g}function Hc(a){hb.test(a.type)&&(a.defaultChecked=a.checked)}function Ob(a,b){if(b in a)return b;for(var d=b.charAt(0).toUpperCase()+b.slice(1),e=b,f=Pb.length;f--;)if(b=Pb[f]+d,b in a)return b;return e}function Ma(a,b){a=b||a;return"none"===c.css(a,"display")||!c.contains(a.ownerDocument,a)}function Qb(a,b){for(var d,e,f,g=[],k=0,m=a.length;k<m;k++)e=a[k],e.style&&(g[k]=c._data(e,"olddisplay"),d=e.style.display,b?(g[k]||"none"!==d||(e.style.display=""),""===e.style.display&&Ma(e)&&
(g[k]=c._data(e,"olddisplay",Rb(e.nodeName)))):g[k]||(f=Ma(e),(d&&"none"!==d||!f)&&c._data(e,"olddisplay",f?d:c.css(e,"display"))));for(k=0;k<m;k++)e=a[k],!e.style||b&&"none"!==e.style.display&&""!==e.style.display||(e.style.display=b?g[k]||"":"none");return a}function Sb(a,b,d){return(a=Ic.exec(b))?Math.max(0,a[1]-(d||0))+(a[2]||"px"):b}function Tb(a,b,d,e,f){b=d===(e?"border":"content")?4:"width"===b?1:0;for(var g=0;4>b;b+=2)"margin"===d&&(g+=c.css(a,d+wa[b],!0,f)),e?("content"===d&&(g-=c.css(a,
	"padding"+wa[b],!0,f)),"margin"!==d&&(g-=c.css(a,"border"+wa[b]+"Width",!0,f))):(g+=c.css(a,"padding"+wa[b],!0,f),"padding"!==d&&(g+=c.css(a,"border"+wa[b]+"Width",!0,f)));return g}function Ub(a,b,d){var e=!0,f="width"===b?a.offsetWidth:a.offsetHeight,g=Fa(a),k=c.support.boxSizing&&"border-box"===c.css(a,"boxSizing",!1,g);if(0>=f||null==f){f=Ga(a,b,g);if(0>f||null==f)f=a.style[b];if(Ua.test(f))return f;e=k&&(c.support.boxSizingReliable||f===a.style[b]);f=parseFloat(f)||0}return f+Tb(a,b,d||(k?"border":
	"content"),e,g)+"px"}function Rb(a){var b=C,d=Vb[a];d||(d=Wb(a,b),"none"!==d&&d||(Na=(Na||c("<iframe frameborder='0' width='0' height='0'/>").css("cssText","display:block !important")).appendTo(b.documentElement),b=(Na[0].contentWindow||Na[0].contentDocument).document,b.write("<!doctype html><html><body>"),b.close(),d=Wb(a,b),Na.detach()),Vb[a]=d);return d}function Wb(a,b){a=c(b.createElement(a)).appendTo(b.body);b=c.css(a[0],"display");a.remove();return b}function ib(a,b,d,e){var f;if(c.isArray(b))c.each(b,
	function(g,k){d||Jc.test(a)?e(a,k):ib(a+"["+("object"===typeof k?g:"")+"]",k,d,e)});else if(d||"object"!==c.type(b))e(a,b);else for(f in b)ib(a+"["+f+"]",b[f],d,e)}function Xb(a){return function(b,d){"string"!==typeof b&&(d=b,b="*");var e=0,f=b.toLowerCase().match(sa)||[];if(c.isFunction(d))for(;b=f[e++];)"+"===b[0]?(b=b.slice(1)||"*",(a[b]=a[b]||[]).unshift(d)):(a[b]=a[b]||[]).push(d)}}function Yb(a,b,d,e){function f(m){var p;g[m]=!0;c.each(a[m]||[],function(q,v){q=v(b,d,e);if("string"===typeof q&&
	!k&&!g[q])return b.dataTypes.unshift(q),f(q),!1;if(k)return!(p=q)});return p}var g={},k=a===jb;return f(b.dataTypes[0])||!g["*"]&&f("*")}function kb(a,b){var d,e,f=c.ajaxSettings.flatOptions||{};for(e in b)b[e]!==y&&((f[e]?a:d||(d={}))[e]=b[e]);d&&c.extend(!0,a,d);return a}function Zb(){try{return new F.XMLHttpRequest}catch(a){}}function $b(){setTimeout(function(){Ha=y});return Ha=c.now()}function Kc(a,b){c.each(b,function(d,e){for(var f=(Oa[d]||[]).concat(Oa["*"]),g=0,k=f.length;g<k&&!f[g].call(a,
	d,e);g++);})}function ac(a,b,d){var e,f=0,g=Va.length,k=c.Deferred().always(function(){delete m.elem}),m=function(){if(e)return!1;var q=Ha||$b();q=Math.max(0,p.startTime+p.duration-q);for(var v=1-(q/p.duration||0),t=0,w=p.tweens.length;t<w;t++)p.tweens[t].run(v);k.notifyWith(a,[p,v,q]);if(1>v&&w)return q;k.resolveWith(a,[p]);return!1},p=k.promise({elem:a,props:c.extend({},b),opts:c.extend(!0,{specialEasing:{}},d),originalProperties:b,originalOptions:d,startTime:Ha||$b(),duration:d.duration,tweens:[],
	createTween:function(q,v){q=c.Tween(a,p.opts,q,v,p.opts.specialEasing[q]||p.opts.easing);p.tweens.push(q);return q},stop:function(q){var v=0,t=q?p.tweens.length:0;if(e)return this;for(e=!0;v<t;v++)p.tweens[v].run(1);q?k.resolveWith(a,[p,q]):k.rejectWith(a,[p,q]);return this}});d=p.props;for(Lc(d,p.opts.specialEasing);f<g;f++)if(b=Va[f].call(p,a,d,p.opts))return b;Kc(p,d);c.isFunction(p.opts.start)&&p.opts.start.call(a,p);c.fx.timer(c.extend(m,{elem:a,anim:p,queue:p.opts.queue}));return p.progress(p.opts.progress).done(p.opts.done,
	p.opts.complete).fail(p.opts.fail).always(p.opts.always)}function Lc(a,b){var d,e;for(d in a){var f=c.camelCase(d);var g=b[f];var k=a[d];c.isArray(k)&&(g=k[1],k=a[d]=k[0]);d!==f&&(a[f]=k,delete a[d]);if((e=c.cssHooks[f])&&"expand"in e)for(d in k=e.expand(k),delete a[f],k)d in a||(a[d]=k[d],b[d]=g);else b[f]=g}}function ha(a,b,d,e,f){return new ha.prototype.init(a,b,d,e,f)}function Wa(a,b){var d={height:a},e=0;for(b=b?1:0;4>e;e+=2-b){var f=wa[e];d["margin"+f]=d["padding"+f]=a}b&&(d.opacity=d.width=
	a);return d}function bc(a){return c.isWindow(a)?a:9===a.nodeType?a.defaultView||a.parentWindow:!1}var Xa,qa=typeof y,C=F.document,Mc=F.location,Nc=F.jQuery,Oc=F.$,Ya={},Da=[],cc=Da.concat,lb=Da.push,xa=Da.slice,dc=Da.indexOf,Pc=Ya.toString,Pa=Ya.hasOwnProperty,mb="1.9.1".trim,c=function(a,b){return new c.fn.init(a,b,Qc)},Za=/[+-]?(?:\d*\.|)\d+(?:[eE][+-]?\d+|)/.source,sa=/\S+/g,Rc=/^[\s\uFEFF\xA0]+|[\s\uFEFF\xA0]+$/g,Sc=/^(?:(<[\w\W]+>)[^>]*|#([\w-]*))$/,ec=/^<(\w+)\s*\/?>(?:<\/\1>|)$/,Tc=/^[\],:{}\s]*$/,
	Uc=/(?:^|:|,)(?:\s*\[)+/g,Vc=/\\(?:["\\\/bfnrt]|u[\da-fA-F]{4})/g,Wc=/"[^"\\\r\n]*"|true|false|null|-?(?:\d+\.|)\d+(?:[eE][+-]?\d+|)/g,Xc=/^-ms-/,Yc=/-([\da-z])/gi,Zc=function(a,b){return b.toUpperCase()},ta=function(a){if(C.addEventListener||"load"===a.type||"complete"===C.readyState)fc(),c.ready()},fc=function(){C.addEventListener?(C.removeEventListener("DOMContentLoaded",ta,!1),F.removeEventListener("load",ta,!1)):(C.detachEvent("onreadystatechange",ta),F.detachEvent("onload",ta))};c.fn=c.prototype=
	{jquery:"1.9.1",constructor:c,init:function(a,b,d){if(!a)return this;if("string"===typeof a){var e="<"===a.charAt(0)&&">"===a.charAt(a.length-1)&&3<=a.length?[null,a,null]:Sc.exec(a);if(!e||!e[1]&&b)return!b||b.jquery?(b||d).find(a):this.constructor(b).find(a);if(e[1]){if(b=b instanceof c?b[0]:b,c.merge(this,c.parseHTML(e[1],b&&b.nodeType?b.ownerDocument||b:C,!0)),ec.test(e[1])&&c.isPlainObject(b))for(e in b)if(c.isFunction(this[e]))this[e](b[e]);else this.attr(e,b[e])}else{if((b=C.getElementById(e[2]))&&
			b.parentNode){if(b.id!==e[2])return d.find(a);this.length=1;this[0]=b}this.context=C;this.selector=a}return this}if(a.nodeType)return this.context=this[0]=a,this.length=1,this;if(c.isFunction(a))return d.ready(a);a.selector!==y&&(this.selector=a.selector,this.context=a.context);return c.makeArray(a,this)},selector:"",length:0,size:function(){return this.length},toArray:function(){return xa.call(this)},get:function(a){return null==a?this.toArray():0>a?this[this.length+a]:this[a]},pushStack:function(a){a=
			c.merge(this.constructor(),a);a.prevObject=this;a.context=this.context;return a},each:function(a,b){return c.each(this,a,b)},ready:function(a){c.ready.promise().done(a);return this},slice:function(){return this.pushStack(xa.apply(this,arguments))},first:function(){return this.eq(0)},last:function(){return this.eq(-1)},eq:function(a){var b=this.length;a=+a+(0>a?b:0);return this.pushStack(0<=a&&a<b?[this[a]]:[])},map:function(a){return this.pushStack(c.map(this,function(b,d){return a.call(b,d,b)}))},
		end:function(){return this.prevObject||this.constructor(null)},push:lb,sort:[].sort,splice:[].splice};c.fn.init.prototype=c.fn;c.extend=c.fn.extend=function(){var a,b,d,e=arguments[0]||{},f=1,g=arguments.length,k=!1;"boolean"===typeof e&&(k=e,e=arguments[1]||{},f=2);"object"===typeof e||c.isFunction(e)||(e={});g===f&&(e=this,--f);for(;f<g;f++)if(null!=(d=arguments[f]))for(b in d){var m=e[b];var p=d[b];e!==p&&(k&&p&&(c.isPlainObject(p)||(a=c.isArray(p)))?(a?(a=!1,m=m&&c.isArray(m)?m:[]):m=m&&c.isPlainObject(m)?
	m:{},e[b]=c.extend(k,m,p)):p!==y&&(e[b]=p))}return e};c.extend({noConflict:function(a){F.$===c&&(F.$=Oc);a&&F.jQuery===c&&(F.jQuery=Nc);return c},isReady:!1,readyWait:1,holdReady:function(a){a?c.readyWait++:c.ready(!0)},ready:function(a){if(!0===a?!--c.readyWait:!c.isReady){if(!C.body)return setTimeout(c.ready);c.isReady=!0;!0!==a&&0<--c.readyWait||(Xa.resolveWith(C,[c]),c.fn.trigger&&c(C).trigger("ready").off("ready"))}},isFunction:function(a){return"function"===c.type(a)},isArray:Array.isArray||
		function(a){return"array"===c.type(a)},isWindow:function(a){return null!=a&&a==a.window},isNumeric:function(a){return!isNaN(parseFloat(a))&&isFinite(a)},type:function(a){return null==a?String(a):"object"===typeof a||"function"===typeof a?Ya[Pc.call(a)]||"object":typeof a},isPlainObject:function(a){if(!a||"object"!==c.type(a)||a.nodeType||c.isWindow(a))return!1;try{if(a.constructor&&!Pa.call(a,"constructor")&&!Pa.call(a.constructor.prototype,"isPrototypeOf"))return!1}catch(d){return!1}for(var b in a);
		return b===y||Pa.call(a,b)},isEmptyObject:function(a){for(var b in a)return!1;return!0},error:function(a){throw Error(a);},parseHTML:function(a,b,d){if(!a||"string"!==typeof a)return null;"boolean"===typeof b&&(d=b,b=!1);b=b||C;var e=ec.exec(a);d=!d&&[];if(e)return[b.createElement(e[1])];e=c.buildFragment([a],b,d);d&&c(d).remove();return c.merge([],e.childNodes)},parseJSON:function(a){if(F.JSON&&F.JSON.parse)return F.JSON.parse(a);if(null===a)return a;if("string"===typeof a&&(a=c.trim(a))&&Tc.test(a.replace(Vc,
		"@").replace(Wc,"]").replace(Uc,"")))return(new Function("return "+a))();c.error("Invalid JSON: "+a)},parseXML:function(a){if(!a||"string"!==typeof a)return null;try{if(F.DOMParser){var b=new DOMParser;var d=b.parseFromString(a,"text/xml")}else d=new ActiveXObject("Microsoft.XMLDOM"),d.async="false",d.loadXML(a)}catch(e){d=y}d&&d.documentElement&&!d.getElementsByTagName("parsererror").length||c.error("Invalid XML: "+a);return d},noop:function(){},globalEval:function(a){a&&c.trim(a)&&(F.execScript||
		function(b){F.eval.call(F,b)})(a)},camelCase:function(a){return a.replace(Xc,"ms-").replace(Yc,Zc)},nodeName:function(a,b){return a.nodeName&&a.nodeName.toLowerCase()===b.toLowerCase()},each:function(a,b,d){var e=0,f=a.length;var g=eb(a);if(d)if(g)for(;e<f&&(g=b.apply(a[e],d),!1!==g);e++);else for(e in a){if(g=b.apply(a[e],d),!1===g)break}else if(g)for(;e<f&&(g=b.call(a[e],e,a[e]),!1!==g);e++);else for(e in a)if(g=b.call(a[e],e,a[e]),!1===g)break;return a},trim:mb&&!mb.call("\ufeff\u00a0")?function(a){return null==
	a?"":mb.call(a)}:function(a){return null==a?"":(a+"").replace(Rc,"")},makeArray:function(a,b){b=b||[];null!=a&&(eb(Object(a))?c.merge(b,"string"===typeof a?[a]:a):lb.call(b,a));return b},inArray:function(a,b,d){if(b){if(dc)return dc.call(b,a,d);var e=b.length;for(d=d?0>d?Math.max(0,e+d):d:0;d<e;d++)if(d in b&&b[d]===a)return d}return-1},merge:function(a,b){var d=b.length,e=a.length,f=0;if("number"===typeof d)for(;f<d;f++)a[e++]=b[f];else for(;b[f]!==y;)a[e++]=b[f++];a.length=e;return a},grep:function(a,
																																																																																																																															  b,d){var e=[],f=0,g=a.length;for(d=!!d;f<g;f++){var k=!!b(a[f],f);d!==k&&e.push(a[f])}return e},map:function(a,b,d){var e=0,f=a.length,g=[];if(eb(a))for(;e<f;e++){var k=b(a[e],e,d);null!=k&&(g[g.length]=k)}else for(e in a)k=b(a[e],e,d),null!=k&&(g[g.length]=k);return cc.apply([],g)},guid:1,proxy:function(a,b){if("string"===typeof b){var d=a[b];b=a;a=d}if(!c.isFunction(a))return y;var e=xa.call(arguments,2);d=function(){return a.apply(b||this,e.concat(xa.call(arguments)))};d.guid=a.guid=a.guid||c.guid++;
		return d},access:function(a,b,d,e,f,g,k){var m=0,p=a.length,q=null==d;if("object"===c.type(d))for(m in f=!0,d)c.access(a,b,m,d[m],!0,g,k);else if(e!==y&&(f=!0,c.isFunction(e)||(k=!0),q&&(k?(b.call(a,e),b=null):(q=b,b=function(v,t,w){return q.call(c(v),w)})),b))for(;m<p;m++)b(a[m],d,k?e:e.call(a[m],m,b(a[m],d)));return f?a:q?b.call(a):p?b(a[0],d):g},now:function(){return(new Date).getTime()}});c.ready.promise=function(a){if(!Xa)if(Xa=c.Deferred(),"complete"===C.readyState)setTimeout(c.ready);else if(C.addEventListener)C.addEventListener("DOMContentLoaded",
	ta,!1),F.addEventListener("load",ta,!1);else{C.attachEvent("onreadystatechange",ta);F.attachEvent("onload",ta);var b=!1;try{b=null==F.frameElement&&C.documentElement}catch(d){}b&&b.doScroll&&function e(){if(!c.isReady){try{b.doScroll("left")}catch(f){return setTimeout(e,50)}fc();c.ready()}}()}return Xa.promise(a)};c.each("Boolean Number String Function Array Date RegExp Object Error".split(" "),function(a,b){Ya["[object "+b+"]"]=b.toLowerCase()});var Qc=c(C);var Db={};c.Callbacks=function(a){a="string"===
typeof a?Db[a]||Bc(a):c.extend({},a);var b,d,e,f,g,k,m=[],p=!a.once&&[],q=function(t){d=a.memory&&t;e=!0;g=k||0;k=0;f=m.length;for(b=!0;m&&g<f;g++)if(!1===m[g].apply(t[0],t[1])&&a.stopOnFalse){d=!1;break}b=!1;m&&(p?p.length&&q(p.shift()):d?m=[]:v.disable())},v={add:function(){if(m){var t=m.length;(function Q(G){c.each(G,function(ba,U){ba=c.type(U);"function"===ba?a.unique&&v.has(U)||m.push(U):U&&U.length&&"string"!==ba&&Q(U)})})(arguments);b?f=m.length:d&&(k=t,q(d))}return this},remove:function(){m&&
	c.each(arguments,function(t,w){for(var G;-1<(G=c.inArray(w,m,G));)m.splice(G,1),b&&(G<=f&&f--,G<=g&&g--)});return this},has:function(t){return t?-1<c.inArray(t,m):!(!m||!m.length)},empty:function(){m=[];return this},disable:function(){m=p=d=y;return this},disabled:function(){return!m},lock:function(){p=y;d||v.disable();return this},locked:function(){return!p},fireWith:function(t,w){w=w||[];w=[t,w.slice?w.slice():w];!m||e&&!p||(b?p.push(w):q(w));return this},fire:function(){v.fireWith(this,arguments);
		return this},fired:function(){return!!e}};return v};c.extend({Deferred:function(a){var b=[["resolve","done",c.Callbacks("once memory"),"resolved"],["reject","fail",c.Callbacks("once memory"),"rejected"],["notify","progress",c.Callbacks("memory")]],d="pending",e={state:function(){return d},always:function(){f.done(arguments).fail(arguments);return this},then:function(){var g=arguments;return c.Deferred(function(k){c.each(b,function(m,p){var q=p[0],v=c.isFunction(g[m])&&g[m];f[p[1]](function(){var t=
			v&&v.apply(this,arguments);if(t&&c.isFunction(t.promise))t.promise().done(k.resolve).fail(k.reject).progress(k.notify);else k[q+"With"](this===e?k.promise():this,v?[t]:arguments)})});g=null}).promise()},promise:function(g){return null!=g?c.extend(g,e):e}},f={};e.pipe=e.then;c.each(b,function(g,k){var m=k[2],p=k[3];e[k[1]]=m.add;p&&m.add(function(){d=p},b[g^1][2].disable,b[2][2].lock);f[k[0]]=function(){f[k[0]+"With"](this===f?e:this,arguments);return this};f[k[0]+"With"]=m.fireWith});e.promise(f);
		a&&a.call(f,f);return f},when:function(a){var b=0,d=xa.call(arguments),e=d.length,f=1!==e||a&&c.isFunction(a.promise)?e:0,g=1===f?a:c.Deferred(),k=function(v,t,w){return function(G){t[v]=this;w[v]=1<arguments.length?xa.call(arguments):G;w===p?g.notifyWith(t,w):--f||g.resolveWith(t,w)}},m;if(1<e){var p=Array(e);var q=Array(e);for(m=Array(e);b<e;b++)d[b]&&c.isFunction(d[b].promise)?d[b].promise().done(k(b,m,d)).fail(g.reject).progress(k(b,q,p)):--f}f||g.resolveWith(m,d);return g.promise()}});c.support=
	function(){var a,b,d=C.createElement("div");d.setAttribute("className","t");d.innerHTML="  <link/><table></table><a href='/a'>a</a><input type='checkbox'/>";var e=d.getElementsByTagName("*");var f=d.getElementsByTagName("a")[0];if(!e||!f||!e.length)return{};var g=C.createElement("select");var k=g.appendChild(C.createElement("option"));e=d.getElementsByTagName("input")[0];f.style.cssText="top:1px;float:left;opacity:.5";var m={getSetAttribute:"t"!==d.className,leadingWhitespace:3===d.firstChild.nodeType,
		tbody:!d.getElementsByTagName("tbody").length,htmlSerialize:!!d.getElementsByTagName("link").length,style:/top/.test(f.getAttribute("style")),hrefNormalized:"/a"===f.getAttribute("href"),opacity:/^0.5/.test(f.style.opacity),cssFloat:!!f.style.cssFloat,checkOn:!!e.value,optSelected:k.selected,enctype:!!C.createElement("form").enctype,html5Clone:"<:nav></:nav>"!==C.createElement("nav").cloneNode(!0).outerHTML,boxModel:"CSS1Compat"===C.compatMode,deleteExpando:!0,noCloneEvent:!0,inlineBlockNeedsLayout:!1,
		shrinkWrapBlocks:!1,reliableMarginRight:!0,boxSizingReliable:!0,pixelPosition:!1};e.checked=!0;m.noCloneChecked=e.cloneNode(!0).checked;g.disabled=!0;m.optDisabled=!k.disabled;try{delete d.test}catch(p){m.deleteExpando=!1}e=C.createElement("input");e.setAttribute("value","");m.input=""===e.getAttribute("value");e.value="t";e.setAttribute("type","radio");m.radioValue="t"===e.value;e.setAttribute("checked","t");e.setAttribute("name","t");f=C.createDocumentFragment();f.appendChild(e);m.appendChecked=
		e.checked;m.checkClone=f.cloneNode(!0).cloneNode(!0).lastChild.checked;d.attachEvent&&(d.attachEvent("onclick",function(){m.noCloneEvent=!1}),d.cloneNode(!0).click());for(b in{submit:!0,change:!0,focusin:!0})d.setAttribute(f="on"+b,"t"),m[b+"Bubbles"]=f in F||!1===d.attributes[f].expando;d.style.backgroundClip="content-box";d.cloneNode(!0).style.backgroundClip="";m.clearCloneStyle="content-box"===d.style.backgroundClip;c(function(){var p=C.getElementsByTagName("body")[0];if(p){var q=C.createElement("div");
		q.style.cssText="border:0;width:0;height:0;position:absolute;top:0;left:-9999px;margin-top:1px";p.appendChild(q).appendChild(d);d.innerHTML="<table><tr><td></td><td>t</td></tr></table>";var v=d.getElementsByTagName("td");v[0].style.cssText="padding:0;margin:0;border:0;display:none";a=0===v[0].offsetHeight;v[0].style.display="";v[1].style.display="none";m.reliableHiddenOffsets=a&&0===v[0].offsetHeight;d.innerHTML="";d.style.cssText="box-sizing:border-box;-moz-box-sizing:border-box;-webkit-box-sizing:border-box;padding:1px;border:1px;display:block;width:4px;margin-top:1%;position:absolute;top:1%;";
		m.boxSizing=4===d.offsetWidth;m.doesNotIncludeMarginInBodyOffset=1!==p.offsetTop;F.getComputedStyle&&(m.pixelPosition="1%"!==(F.getComputedStyle(d,null)||{}).top,m.boxSizingReliable="4px"===(F.getComputedStyle(d,null)||{width:"4px"}).width,v=d.appendChild(C.createElement("div")),v.style.cssText=d.style.cssText="padding:0;margin:0;border:0;display:block;box-sizing:content-box;-moz-box-sizing:content-box;-webkit-box-sizing:content-box;",v.style.marginRight=v.style.width="0",d.style.width="1px",m.reliableMarginRight=
			!parseFloat((F.getComputedStyle(v,null)||{}).marginRight));typeof d.style.zoom!==qa&&(d.style.cssText="padding:0;margin:0;border:0;display:block;box-sizing:content-box;-moz-box-sizing:content-box;-webkit-box-sizing:content-box;width:1px;padding:1px;display:inline;zoom:1",m.inlineBlockNeedsLayout=3===d.offsetWidth,d.style.display="block",d.innerHTML="<div></div>",d.firstChild.style.width="5px",m.shrinkWrapBlocks=3!==d.offsetWidth,m.inlineBlockNeedsLayout&&(p.style.zoom=1));p.removeChild(q);d=null}});
		e=g=f=k=f=e=null;return m}();var Dc=/(?:\{[\s\S]*\}|\[[\s\S]*\])$/,Cc=/([A-Z])/g;c.extend({cache:{},expando:"jQuery"+("1.9.1"+Math.random()).replace(/\D/g,""),noData:{embed:!0,object:"clsid:D27CDB6E-AE6D-11cf-96B8-444553540000",applet:!0},hasData:function(a){a=a.nodeType?c.cache[a[c.expando]]:a[c.expando];return!!a&&!fb(a)},data:function(a,b,d){return Eb(a,b,d)},removeData:function(a,b){return Fb(a,b)},_data:function(a,b,d){return Eb(a,b,d,!0)},_removeData:function(a,b){return Fb(a,b,!0)},acceptData:function(a){if(a.nodeType&&
		1!==a.nodeType&&9!==a.nodeType)return!1;var b=a.nodeName&&c.noData[a.nodeName.toLowerCase()];return!b||!0!==b&&a.getAttribute("classid")===b}});c.fn.extend({data:function(a,b){var d,e=this[0],f=0,g=null;if(a===y){if(this.length&&(g=c.data(e),1===e.nodeType&&!c._data(e,"parsedAttrs"))){for(d=e.attributes;f<d.length;f++){var k=d[f].name;k.indexOf("data-")||(k=c.camelCase(k.slice(5)),Gb(e,k,g[k]))}c._data(e,"parsedAttrs",!0)}return g}return"object"===typeof a?this.each(function(){c.data(this,a)}):c.access(this,
		function(m){if(m===y)return e?Gb(e,a,c.data(e,a)):null;this.each(function(){c.data(this,a,m)})},null,b,1<arguments.length,null,!0)},removeData:function(a){return this.each(function(){c.removeData(this,a)})}});c.extend({queue:function(a,b,d){if(a){b=(b||"fx")+"queue";var e=c._data(a,b);d&&(!e||c.isArray(d)?e=c._data(a,b,c.makeArray(d)):e.push(d));return e||[]}},dequeue:function(a,b){b=b||"fx";var d=c.queue(a,b),e=d.length,f=d.shift(),g=c._queueHooks(a,b),k=function(){c.dequeue(a,b)};"inprogress"===
	f&&(f=d.shift(),e--);if(g.cur=f)"fx"===b&&d.unshift("inprogress"),delete g.stop,f.call(a,k,g);!e&&g&&g.empty.fire()},_queueHooks:function(a,b){var d=b+"queueHooks";return c._data(a,d)||c._data(a,d,{empty:c.Callbacks("once memory").add(function(){c._removeData(a,b+"queue");c._removeData(a,d)})})}});c.fn.extend({queue:function(a,b){var d=2;"string"!==typeof a&&(b=a,a="fx",d--);return arguments.length<d?c.queue(this[0],a):b===y?this:this.each(function(){var e=c.queue(this,a,b);c._queueHooks(this,a);
		"fx"===a&&"inprogress"!==e[0]&&c.dequeue(this,a)})},dequeue:function(a){return this.each(function(){c.dequeue(this,a)})},delay:function(a,b){a=c.fx?c.fx.speeds[a]||a:a;return this.queue(b||"fx",function(d,e){var f=setTimeout(d,a);e.stop=function(){clearTimeout(f)}})},clearQueue:function(a){return this.queue(a||"fx",[])},promise:function(a,b){var d,e=1,f=c.Deferred(),g=this,k=this.length,m=function(){--e||f.resolveWith(g,[g])};"string"!==typeof a&&(b=a,a=y);for(a=a||"fx";k--;)(d=c._data(g[k],a+"queueHooks"))&&
	d.empty&&(e++,d.empty.add(m));m();return f.promise(b)}});var nb=/[\t\r\n]/g,$c=/\r/g,ad=/^(?:input|select|textarea|button|object)$/i,bd=/^(?:a|area)$/i,gc=/^(?:checked|selected|autofocus|autoplay|async|controls|defer|disabled|hidden|loop|multiple|open|readonly|required|scoped)$/i,ob=/^(?:checked|selected)$/i,ya=c.support.getSetAttribute,pb=c.support.input;c.fn.extend({attr:function(a,b){return c.access(this,c.attr,a,b,1<arguments.length)},removeAttr:function(a){return this.each(function(){c.removeAttr(this,
		a)})},prop:function(a,b){return c.access(this,c.prop,a,b,1<arguments.length)},removeProp:function(a){a=c.propFix[a]||a;return this.each(function(){try{this[a]=y,delete this[a]}catch(b){}})},addClass:function(a){var b,d,e,f=0,g=this.length;var k="string"===typeof a&&a;if(c.isFunction(a))return this.each(function(p){c(this).addClass(a.call(this,p,this.className))});if(k)for(k=(a||"").match(sa)||[];f<g;f++){var m=this[f];if(b=1===m.nodeType&&(m.className?(" "+m.className+" ").replace(nb," "):" ")){for(e=
																																																																																																																																	0;d=k[e++];)0>b.indexOf(" "+d+" ")&&(b+=d+" ");m.className=c.trim(b)}}return this},removeClass:function(a){var b,d,e,f=0,g=this.length;var k=0===arguments.length||"string"===typeof a&&a;if(c.isFunction(a))return this.each(function(p){c(this).removeClass(a.call(this,p,this.className))});if(k)for(k=(a||"").match(sa)||[];f<g;f++){var m=this[f];if(b=1===m.nodeType&&(m.className?(" "+m.className+" ").replace(nb," "):"")){for(e=0;d=k[e++];)for(;0<=b.indexOf(" "+d+" ");)b=b.replace(" "+d+" "," ");m.className=
		a?c.trim(b):""}}return this},toggleClass:function(a,b){var d=typeof a,e="boolean"===typeof b;return c.isFunction(a)?this.each(function(f){c(this).toggleClass(a.call(this,f,this.className,b),b)}):this.each(function(){if("string"===d)for(var f,g=0,k=c(this),m=b,p=a.match(sa)||[];f=p[g++];)m=e?m:!k.hasClass(f),k[m?"addClass":"removeClass"](f);else if(d===qa||"boolean"===d)this.className&&c._data(this,"__className__",this.className),this.className=this.className||!1===a?"":c._data(this,"__className__")||
		""})},hasClass:function(a){a=" "+a+" ";for(var b=0,d=this.length;b<d;b++)if(1===this[b].nodeType&&0<=(" "+this[b].className+" ").replace(nb," ").indexOf(a))return!0;return!1},val:function(a){var b,d,e=this[0];if(arguments.length){var f=c.isFunction(a);return this.each(function(g){var k=c(this);1===this.nodeType&&(g=f?a.call(this,g,k.val()):a,null==g?g="":"number"===typeof g?g+="":c.isArray(g)&&(g=c.map(g,function(m){return null==m?"":m+""})),d=c.valHooks[this.type]||c.valHooks[this.nodeName.toLowerCase()],
	d&&"set"in d&&d.set(this,g,"value")!==y||(this.value=g))})}if(e){if((d=c.valHooks[e.type]||c.valHooks[e.nodeName.toLowerCase()])&&"get"in d&&(b=d.get(e,"value"))!==y)return b;b=e.value;return"string"===typeof b?b.replace($c,""):null==b?"":b}}});c.extend({valHooks:{option:{get:function(a){var b=a.attributes.value;return!b||b.specified?a.value:a.text}},select:{get:function(a){for(var b,d=a.options,e=a.selectedIndex,f=(a="select-one"===a.type||0>e)?null:[],g=a?e+1:d.length,k=0>e?g:a?e:0;k<g;k++)if(b=
				d[k],!(!b.selected&&k!==e||(c.support.optDisabled?b.disabled:null!==b.getAttribute("disabled"))||b.parentNode.disabled&&c.nodeName(b.parentNode,"optgroup"))){b=c(b).val();if(a)return b;f.push(b)}return f},set:function(a,b){var d=c.makeArray(b);c(a).find("option").each(function(){this.selected=0<=c.inArray(c(this).val(),d)});d.length||(a.selectedIndex=-1);return d}}},attr:function(a,b,d){var e;var f=a.nodeType;if(a&&3!==f&&8!==f&&2!==f){if(typeof a.getAttribute===qa)return c.prop(a,b,d);if(f=1!==f||
		!c.isXMLDoc(a)){b=b.toLowerCase();var g=c.attrHooks[b]||(gc.test(b)?cd:Qa)}if(d!==y)if(null===d)c.removeAttr(a,b);else{if(g&&f&&"set"in g&&(e=g.set(a,d,b))!==y)return e;a.setAttribute(b,d+"");return d}else{if(g&&f&&"get"in g&&null!==(e=g.get(a,b)))return e;typeof a.getAttribute!==qa&&(e=a.getAttribute(b));return null==e?y:e}}},removeAttr:function(a,b){var d=0,e=b&&b.match(sa);if(e&&1===a.nodeType)for(;b=e[d++];){var f=c.propFix[b]||b;gc.test(b)?!ya&&ob.test(b)?a[c.camelCase("default-"+b)]=a[f]=!1:
		a[f]=!1:c.attr(a,b,"");a.removeAttribute(ya?b:f)}},attrHooks:{type:{set:function(a,b){if(!c.support.radioValue&&"radio"===b&&c.nodeName(a,"input")){var d=a.value;a.setAttribute("type",b);d&&(a.value=d);return b}}}},propFix:{tabindex:"tabIndex",readonly:"readOnly","for":"htmlFor","class":"className",maxlength:"maxLength",cellspacing:"cellSpacing",cellpadding:"cellPadding",rowspan:"rowSpan",colspan:"colSpan",usemap:"useMap",frameborder:"frameBorder",contenteditable:"contentEditable"},prop:function(a,
																																																																																																																															 b,d){var e,f=a.nodeType;if(a&&3!==f&&8!==f&&2!==f){if(1!==f||!c.isXMLDoc(a)){b=c.propFix[b]||b;var g=c.propHooks[b]}return d!==y?g&&"set"in g&&(e=g.set(a,d,b))!==y?e:a[b]=d:g&&"get"in g&&null!==(e=g.get(a,b))?e:a[b]}},propHooks:{tabIndex:{get:function(a){var b=a.getAttributeNode("tabindex");return b&&b.specified?parseInt(b.value,10):ad.test(a.nodeName)||bd.test(a.nodeName)&&a.href?0:y}}}});var cd={get:function(a,b){var d=c.prop(a,b),e="boolean"===typeof d&&a.getAttribute(b);return(a="boolean"===typeof d?
		pb&&ya?null!=e:ob.test(b)?a[c.camelCase("default-"+b)]:!!e:a.getAttributeNode(b))&&!1!==a.value?b.toLowerCase():y},set:function(a,b,d){!1===b?c.removeAttr(a,d):pb&&ya||!ob.test(d)?a.setAttribute(!ya&&c.propFix[d]||d,d):a[c.camelCase("default-"+d)]=a[d]=!0;return d}};pb&&ya||(c.attrHooks.value={get:function(a,b){b=a.getAttributeNode(b);return c.nodeName(a,"input")?a.defaultValue:b&&b.specified?b.value:y},set:function(a,b,d){if(c.nodeName(a,"input"))a.defaultValue=b;else return Qa&&Qa.set(a,b,d)}});
	if(!ya){var Qa=c.valHooks.button={get:function(a,b){return(a=a.getAttributeNode(b))&&("id"===b||"name"===b||"coords"===b?""!==a.value:a.specified)?a.value:y},set:function(a,b,d){var e=a.getAttributeNode(d);e||a.setAttributeNode(e=a.ownerDocument.createAttribute(d));e.value=b+="";return"value"===d||b===a.getAttribute(d)?b:y}};c.attrHooks.contenteditable={get:Qa.get,set:function(a,b,d){Qa.set(a,""===b?!1:b,d)}};c.each(["width","height"],function(a,b){c.attrHooks[b]=c.extend(c.attrHooks[b],{set:function(d,
																																																																																																																															  e){if(""===e)return d.setAttribute(b,"auto"),e}})})}c.support.hrefNormalized||(c.each(["href","src","width","height"],function(a,b){c.attrHooks[b]=c.extend(c.attrHooks[b],{get:function(d){d=d.getAttribute(b,2);return null==d?y:d}})}),c.each(["href","src"],function(a,b){c.propHooks[b]={get:function(d){return d.getAttribute(b,4)}}}));c.support.style||(c.attrHooks.style={get:function(a){return a.style.cssText||y},set:function(a,b){return a.style.cssText=b+""}});c.support.optSelected||(c.propHooks.selected=
		c.extend(c.propHooks.selected,{get:function(a){if(a=a.parentNode)a.selectedIndex,a.parentNode&&a.parentNode.selectedIndex;return null}}));c.support.enctype||(c.propFix.enctype="encoding");c.support.checkOn||c.each(["radio","checkbox"],function(){c.valHooks[this]={get:function(a){return null===a.getAttribute("value")?"on":a.value}}});c.each(["radio","checkbox"],function(){c.valHooks[this]=c.extend(c.valHooks[this],{set:function(a,b){if(c.isArray(b))return a.checked=0<=c.inArray(c(a).val(),b)}})});
	var qb=/^(?:input|select|textarea)$/i,dd=/^key/,ed=/^(?:mouse|contextmenu)|click/,hc=/^(?:focusinfocus|focusoutblur)$/,ic=/^([^.]*)(?:\.(.+)|)$/;c.event={global:{},add:function(a,b,d,e,f){var g,k,m,p,q;if(k=c._data(a)){if(d.handler){var v=d;d=v.handler;f=v.selector}d.guid||(d.guid=c.guid++);(g=k.events)||(g=k.events={});(m=k.handle)||(m=k.handle=function(Q){return typeof c===qa||Q&&c.event.triggered===Q.type?y:c.event.dispatch.apply(m.elem,arguments)},m.elem=a);b=(b||"").match(sa)||[""];for(k=b.length;k--;){var t=
			ic.exec(b[k])||[];var w=p=t[1];var G=(t[2]||"").split(".").sort();t=c.event.special[w]||{};w=(f?t.delegateType:t.bindType)||w;t=c.event.special[w]||{};p=c.extend({type:w,origType:p,data:e,handler:d,guid:d.guid,selector:f,needsContext:f&&c.expr.match.needsContext.test(f),namespace:G.join(".")},v);(q=g[w])||(q=g[w]=[],q.delegateCount=0,t.setup&&!1!==t.setup.call(a,e,G,m)||(a.addEventListener?a.addEventListener(w,m,!1):a.attachEvent&&a.attachEvent("on"+w,m)));t.add&&(t.add.call(a,p),p.handler.guid||
		(p.handler.guid=d.guid));f?q.splice(q.delegateCount++,0,p):q.push(p);c.event.global[w]=!0}a=null}},remove:function(a,b,d,e,f){var g,k,m,p,q,v=c.hasData(a)&&c._data(a);if(v&&(p=v.events)){b=(b||"").match(sa)||[""];for(m=b.length;m--;){var t=ic.exec(b[m])||[];var w=q=t[1];var G=(t[2]||"").split(".").sort();if(w){var Q=c.event.special[w]||{};w=(e?Q.delegateType:Q.bindType)||w;var ba=p[w]||[];t=t[2]&&new RegExp("(^|\\.)"+G.join("\\.(?:.*\\.|)")+"(\\.|$)");for(k=g=ba.length;g--;){var U=ba[g];!f&&q!==U.origType||
		d&&d.guid!==U.guid||t&&!t.test(U.namespace)||e&&e!==U.selector&&("**"!==e||!U.selector)||(ba.splice(g,1),U.selector&&ba.delegateCount--,Q.remove&&Q.remove.call(a,U))}k&&!ba.length&&(Q.teardown&&!1!==Q.teardown.call(a,G,v.handle)||c.removeEvent(a,w,v.handle),delete p[w])}else for(w in p)c.event.remove(a,w+b[m],d,e,!0)}c.isEmptyObject(p)&&(delete v.handle,c._removeData(a,"events"))}},trigger:function(a,b,d,e){var f,g,k=[d||C],m=Pa.call(a,"type")?a.type:a;var p=Pa.call(a,"namespace")?a.namespace.split("."):
			[];var q=f=d=d||C;if(3!==d.nodeType&&8!==d.nodeType&&!hc.test(m+c.event.triggered)){0<=m.indexOf(".")&&(p=m.split("."),m=p.shift(),p.sort());var v=0>m.indexOf(":")&&"on"+m;a=a[c.expando]?a:new c.Event(m,"object"===typeof a&&a);a.isTrigger=!0;a.namespace=p.join(".");a.namespace_re=a.namespace?new RegExp("(^|\\.)"+p.join("\\.(?:.*\\.|)")+"(\\.|$)"):null;a.result=y;a.target||(a.target=d);b=null==b?[a]:c.makeArray(b,[a]);p=c.event.special[m]||{};if(e||!p.trigger||!1!==p.trigger.apply(d,b)){if(!e&&!p.noBubble&&
			!c.isWindow(d)){var t=p.delegateType||m;hc.test(t+m)||(q=q.parentNode);for(;q;q=q.parentNode)k.push(q),f=q;f===(d.ownerDocument||C)&&k.push(f.defaultView||f.parentWindow||F)}for(g=0;(q=k[g++])&&!a.isPropagationStopped();)a.type=1<g?t:p.bindType||m,(f=(c._data(q,"events")||{})[a.type]&&c._data(q,"handle"))&&f.apply(q,b),(f=v&&q[v])&&c.acceptData(q)&&f.apply&&!1===f.apply(q,b)&&a.preventDefault();a.type=m;if(!(e||a.isDefaultPrevented()||p._default&&!1!==p._default.apply(d.ownerDocument,b)||"click"===
			m&&c.nodeName(d,"a"))&&c.acceptData(d)&&v&&d[m]&&!c.isWindow(d)){(f=d[v])&&(d[v]=null);c.event.triggered=m;try{d[m]()}catch(w){}c.event.triggered=y;f&&(d[v]=f)}return a.result}}},dispatch:function(a){a=c.event.fix(a);var b,d,e,f=xa.call(arguments);var g=(c._data(this,"events")||{})[a.type]||[];var k=c.event.special[a.type]||{};f[0]=a;a.delegateTarget=this;if(!k.preDispatch||!1!==k.preDispatch.call(this,a)){var m=c.event.handlers.call(this,a,g);for(g=0;(d=m[g++])&&!a.isPropagationStopped();)for(a.currentTarget=
																																																																																																																																   d.elem,e=0;(b=d.handlers[e++])&&!a.isImmediatePropagationStopped();)if(!a.namespace_re||a.namespace_re.test(b.namespace))a.handleObj=b,a.data=b.data,b=((c.event.special[b.origType]||{}).handle||b.handler).apply(d.elem,f),b!==y&&!1===(a.result=b)&&(a.preventDefault(),a.stopPropagation());k.postDispatch&&k.postDispatch.call(this,a);return a.result}},handlers:function(a,b){var d,e=[],f=b.delegateCount,g=a.target;if(f&&g.nodeType&&(!a.button||"click"!==a.type))for(;g!=this;g=g.parentNode||this)if(1===
			g.nodeType&&(!0!==g.disabled||"click"!==a.type)){var k=[];for(d=0;d<f;d++){var m=b[d];var p=m.selector+" ";k[p]===y&&(k[p]=m.needsContext?0<=c(p,this).index(g):c.find(p,this,null,[g]).length);k[p]&&k.push(m)}k.length&&e.push({elem:g,handlers:k})}f<b.length&&e.push({elem:this,handlers:b.slice(f)});return e},fix:function(a){if(a[c.expando])return a;var b=a.type;var d=a,e=this.fixHooks[b];e||(this.fixHooks[b]=e=ed.test(b)?this.mouseHooks:dd.test(b)?this.keyHooks:{});var f=e.props?this.props.concat(e.props):
			this.props;a=new c.Event(d);for(b=f.length;b--;){var g=f[b];a[g]=d[g]}a.target||(a.target=d.srcElement||C);3===a.target.nodeType&&(a.target=a.target.parentNode);a.metaKey=!!a.metaKey;return e.filter?e.filter(a,d):a},props:"altKey bubbles cancelable ctrlKey currentTarget eventPhase metaKey relatedTarget shiftKey target timeStamp view which".split(" "),fixHooks:{},keyHooks:{props:["char","charCode","key","keyCode"],filter:function(a,b){null==a.which&&(a.which=null!=b.charCode?b.charCode:b.keyCode);
				return a}},mouseHooks:{props:"button buttons clientX clientY fromElement offsetX offsetY pageX pageY screenX screenY toElement".split(" "),filter:function(a,b){var d=b.button,e=b.fromElement;if(null==a.pageX&&null!=b.clientX){var f=a.target.ownerDocument||C;var g=f.documentElement;f=f.body;a.pageX=b.clientX+(g&&g.scrollLeft||f&&f.scrollLeft||0)-(g&&g.clientLeft||f&&f.clientLeft||0);a.pageY=b.clientY+(g&&g.scrollTop||f&&f.scrollTop||0)-(g&&g.clientTop||f&&f.clientTop||0)}!a.relatedTarget&&e&&(a.relatedTarget=
				e===a.target?b.toElement:e);a.which||d===y||(a.which=d&1?1:d&2?3:d&4?2:0);return a}},special:{load:{noBubble:!0},click:{trigger:function(){if(c.nodeName(this,"input")&&"checkbox"===this.type&&this.click)return this.click(),!1}},focus:{trigger:function(){if(this!==C.activeElement&&this.focus)try{return this.focus(),!1}catch(a){}},delegateType:"focusin"},blur:{trigger:function(){if(this===C.activeElement&&this.blur)return this.blur(),!1},delegateType:"focusout"},beforeunload:{postDispatch:function(a){a.result!==
				y&&(a.originalEvent.returnValue=a.result)}}},simulate:function(a,b,d,e){a=c.extend(new c.Event,d,{type:a,isSimulated:!0,originalEvent:{}});e?c.event.trigger(a,null,b):c.event.dispatch.call(b,a);a.isDefaultPrevented()&&d.preventDefault()}};c.removeEvent=C.removeEventListener?function(a,b,d){a.removeEventListener&&a.removeEventListener(b,d,!1)}:function(a,b,d){b="on"+b;a.detachEvent&&(typeof a[b]===qa&&(a[b]=null),a.detachEvent(b,d))};c.Event=function(a,b){if(!(this instanceof c.Event))return new c.Event(a,
		b);a&&a.type?(this.originalEvent=a,this.type=a.type,this.isDefaultPrevented=a.defaultPrevented||!1===a.returnValue||a.getPreventDefault&&a.getPreventDefault()?Ta:Ea):this.type=a;b&&c.extend(this,b);this.timeStamp=a&&a.timeStamp||c.now();this[c.expando]=!0};c.Event.prototype={isDefaultPrevented:Ea,isPropagationStopped:Ea,isImmediatePropagationStopped:Ea,preventDefault:function(){var a=this.originalEvent;this.isDefaultPrevented=Ta;a&&(a.preventDefault?a.preventDefault():a.returnValue=!1)},stopPropagation:function(){var a=
			this.originalEvent;this.isPropagationStopped=Ta;a&&(a.stopPropagation&&a.stopPropagation(),a.cancelBubble=!0)},stopImmediatePropagation:function(){this.isImmediatePropagationStopped=Ta;this.stopPropagation()}};c.each({mouseenter:"mouseover",mouseleave:"mouseout"},function(a,b){c.event.special[a]={delegateType:b,bindType:b,handle:function(d){var e=d.relatedTarget,f=d.handleObj;if(!e||e!==this&&!c.contains(this,e)){d.type=f.origType;var g=f.handler.apply(this,arguments);d.type=b}return g}}});c.support.submitBubbles||
	(c.event.special.submit={setup:function(){if(c.nodeName(this,"form"))return!1;c.event.add(this,"click._submit keypress._submit",function(a){a=a.target;(a=c.nodeName(a,"input")||c.nodeName(a,"button")?a.form:y)&&!c._data(a,"submitBubbles")&&(c.event.add(a,"submit._submit",function(b){b._submit_bubble=!0}),c._data(a,"submitBubbles",!0))})},postDispatch:function(a){a._submit_bubble&&(delete a._submit_bubble,this.parentNode&&!a.isTrigger&&c.event.simulate("submit",this.parentNode,a,!0))},teardown:function(){if(c.nodeName(this,
			"form"))return!1;c.event.remove(this,"._submit")}});c.support.changeBubbles||(c.event.special.change={setup:function(){if(qb.test(this.nodeName)){if("checkbox"===this.type||"radio"===this.type)c.event.add(this,"propertychange._change",function(a){"checked"===a.originalEvent.propertyName&&(this._just_changed=!0)}),c.event.add(this,"click._change",function(a){this._just_changed&&!a.isTrigger&&(this._just_changed=!1);c.event.simulate("change",this,a,!0)});return!1}c.event.add(this,"beforeactivate._change",
			function(a){a=a.target;qb.test(a.nodeName)&&!c._data(a,"changeBubbles")&&(c.event.add(a,"change._change",function(b){!this.parentNode||b.isSimulated||b.isTrigger||c.event.simulate("change",this.parentNode,b,!0)}),c._data(a,"changeBubbles",!0))})},handle:function(a){var b=a.target;if(this!==b||a.isSimulated||a.isTrigger||"radio"!==b.type&&"checkbox"!==b.type)return a.handleObj.handler.apply(this,arguments)},teardown:function(){c.event.remove(this,"._change");return!qb.test(this.nodeName)}});c.support.focusinBubbles||
	c.each({focus:"focusin",blur:"focusout"},function(a,b){var d=0,e=function(f){c.event.simulate(b,f.target,c.event.fix(f),!0)};c.event.special[b]={setup:function(){0===d++&&C.addEventListener(a,e,!0)},teardown:function(){0===--d&&C.removeEventListener(a,e,!0)}}});c.fn.extend({on:function(a,b,d,e,f){var g;if("object"===typeof a){"string"!==typeof b&&(d=d||b,b=y);for(g in a)this.on(g,b,d,a[g],f);return this}null==d&&null==e?(e=b,d=b=y):null==e&&("string"===typeof b?(e=d,d=y):(e=d,d=b,b=y));if(!1===e)e=
			Ea;else if(!e)return this;if(1===f){var k=e;e=function(m){c().off(m);return k.apply(this,arguments)};e.guid=k.guid||(k.guid=c.guid++)}return this.each(function(){c.event.add(this,a,e,d,b)})},one:function(a,b,d,e){return this.on(a,b,d,e,1)},off:function(a,b,d){if(a&&a.preventDefault&&a.handleObj){var e=a.handleObj;c(a.delegateTarget).off(e.namespace?e.origType+"."+e.namespace:e.origType,e.selector,e.handler);return this}if("object"===typeof a){for(e in a)this.off(e,b,a[e]);return this}if(!1===b||"function"===
			typeof b)d=b,b=y;!1===d&&(d=Ea);return this.each(function(){c.event.remove(this,a,d,b)})},bind:function(a,b,d){return this.on(a,null,b,d)},unbind:function(a,b){return this.off(a,null,b)},delegate:function(a,b,d,e){return this.on(b,a,d,e)},undelegate:function(a,b,d){return 1===arguments.length?this.off(a,"**"):this.off(b,a||"**",d)},trigger:function(a,b){return this.each(function(){c.event.trigger(a,b,this)})},triggerHandler:function(a,b){var d=this[0];if(d)return c.event.trigger(a,b,d,!0)}});(function(a,
																																																																																																																																	   b){function d(){var h,n=[];return h=function(l,r){n.push(l+=" ")>N.cacheLength&&delete h[n.shift()];return h[l]=r}}function e(h){h[O]=!0;return h}function f(h){var n=H.createElement("div");try{return h(n)}catch(l){return!1}finally{}}function g(h,n,l,r){var u,z,x,B;(n?n.ownerDocument||n:ra)!==H&&Ra(n);n=n||H;l=l||[];if(!h||"string"!==typeof h)return l;if(1!==(B=n.nodeType)&&9!==B)return[];if(!P&&!r){if(u=fd.exec(h))if(x=u[1])if(9===B)if((z=n.getElementById(x))&&z.parentNode){if(z.id===x)return l.push(z),
		l}else return l;else{if(n.ownerDocument&&(z=n.ownerDocument.getElementById(x))&&Y(n,z)&&z.id===x)return l.push(z),l}else{if(u[2])return Ia.apply(l,Ja.call(n.getElementsByTagName(h),0)),l;if((x=u[3])&&M.getByClassName&&n.getElementsByClassName)return Ia.apply(l,Ja.call(n.getElementsByClassName(x),0)),l}if(M.qsa&&!X.test(h)){u=!0;z=O;x=n;var A=9===B&&h;if(1===B&&"object"!==n.nodeName.toLowerCase()){B=v(h);(u=n.getAttribute("id"))?z=u.replace(gd,"\\$&"):n.setAttribute("id",z);z="[id='"+z+"'] ";for(x=
																																																																																																																																B.length;x--;)B[x]=z+t(B[x]);x=rb.test(h)&&n.parentNode||n;A=B.join(",")}if(A)try{return Ia.apply(l,Ja.call(x.querySelectorAll(A),0)),l}catch(D){}finally{u||n.removeAttribute("id")}}}var I;a:{h=h.replace($a,"$1");z=v(h);if(!r&&1===z.length){u=z[0]=z[0].slice(0);if(2<u.length&&"ID"===(I=u[0]).type&&9===n.nodeType&&!P&&N.relative[u[1].type]){n=N.find.ID(I.matches[0].replace(ua,va),n)[0];if(!n){I=l;break a}h=h.slice(u.shift().value.length)}for(B=ab.needsContext.test(h)?0:u.length;B--;){I=u[B];if(N.relative[x=
		I.type])break;if(x=N.find[x])if(r=x(I.matches[0].replace(ua,va),rb.test(u[0].type)&&n.parentNode||n)){u.splice(B,1);h=r.length&&t(u);if(!h){Ia.apply(l,Ja.call(r,0));I=l;break a}break}}}jc(h,z)(r,n,P,l,rb.test(h));I=l}return I}function k(h,n){var l=n&&h,r=l&&(~n.sourceIndex||-2147483648)-(~h.sourceIndex||-2147483648);if(r)return r;if(l)for(;l=l.nextSibling;)if(l===n)return-1;return h?1:-1}function m(h){return function(n){return"input"===n.nodeName.toLowerCase()&&n.type===h}}function p(h){return function(n){var l=
		n.nodeName.toLowerCase();return("input"===l||"button"===l)&&n.type===h}}function q(h){return e(function(n){n=+n;return e(function(l,r){for(var u,z=h([],l.length,n),x=z.length;x--;)l[u=z[x]]&&(l[u]=!(r[u]=l[u]))})})}function v(h,n){var l,r,u,z,x;if(z=za[h+" "])return n?0:z.slice(0);z=h;var B=[];for(x=N.preFilter;z;){if(!A||(l=hd.exec(z)))l&&(z=z.slice(l[0].length)||z),B.push(r=[]);var A=!1;if(l=id.exec(z))A=l.shift(),r.push({value:A,type:l[0].replace($a," ")}),z=z.slice(A.length);for(u in N.filter)!(l=
		ab[u].exec(z))||x[u]&&!(l=x[u](l))||(A=l.shift(),r.push({value:A,type:u,matches:l}),z=z.slice(A.length));if(!A)break}return n?z.length:z?g.error(h):za(h,B).slice(0)}function t(h){for(var n=0,l=h.length,r="";n<l;n++)r+=h[n].value;return r}function w(h,n,l){var r=n.dir,u=l&&"parentNode"===r,z=ma++;return n.first?function(x,B,A){for(;x=x[r];)if(1===x.nodeType||u)return h(x,B,A)}:function(x,B,A){var I,D,K=R+" "+z;if(A)for(;x=x[r];){if((1===x.nodeType||u)&&h(x,B,A))return!0}else for(;x=x[r];)if(1===x.nodeType||
		u){var S=x[O]||(x[O]={});if((D=S[r])&&D[0]===K){if(!0===(I=D[1])||I===aa)return!0===I}else if(D=S[r]=[K],D[1]=h(x,B,A)||aa,!0===D[1])return!0}}}function G(h){return 1<h.length?function(n,l,r){for(var u=h.length;u--;)if(!h[u](n,l,r))return!1;return!0}:h[0]}function Q(h,n,l,r,u){for(var z,x=[],B=0,A=h.length,I=null!=n;B<A;B++)if(z=h[B])if(!l||l(z,r,u))x.push(z),I&&n.push(B);return x}function ba(h,n,l,r,u,z){r&&!r[O]&&(r=ba(r));u&&!u[O]&&(u=ba(u,z));return e(function(x,B,A,I){var D,K=[],S=[],ja=B.length,
		T;if(!(T=x)){T=n||"*";for(var L=A.nodeType?[A]:A,da=[],W=0,bb=L.length;W<bb;W++)g(T,L[W],da);T=da}T=!h||!x&&n?T:Q(T,K,h,A,I);L=l?u||(x?h:ja||r)?[]:B:T;l&&l(T,L,A,I);if(r){var oa=Q(L,S);r(oa,[],A,I);for(A=oa.length;A--;)if(D=oa[A])L[S[A]]=!(T[S[A]]=D)}if(x){if(u||h){if(u){oa=[];for(A=L.length;A--;)(D=L[A])&&oa.push(T[A]=D);u(null,L=[],oa,I)}for(A=L.length;A--;)(D=L[A])&&-1<(oa=u?sb.call(x,D):K[A])&&(x[oa]=!(B[oa]=D))}}else L=Q(L===B?L.splice(ja,L.length):L),u?u(null,B,L,I):Ia.apply(B,L)})}function U(h){var n,
		l,r=h.length,u=N.relative[h[0].type];var z=u||N.relative[" "];for(var x=u?1:0,B=w(function(D){return D===n},z,!0),A=w(function(D){return-1<sb.call(n,D)},z,!0),I=[function(D,K,S){return!u&&(S||K!==V)||((n=K).nodeType?B(D,K,S):A(D,K,S))}];x<r;x++)if(z=N.relative[h[x].type])I=[w(G(I),z)];else{z=N.filter[h[x].type].apply(null,h[x].matches);if(z[O]){for(l=++x;l<r&&!N.relative[h[l].type];l++);return ba(1<x&&G(I),1<x&&t(h.slice(0,x-1)).replace($a,"$1"),z,x<l&&U(h.slice(x,l)),l<r&&U(h=h.slice(l)),l<r&&t(h))}I.push(z)}return G(I)}
		function ka(h,n){var l=0,r=0<n.length,u=0<h.length,z=function(x,B,A,I,D){var K,S,ja=[],T=0,L="0",da=x&&[],W=null!=D,bb=V,oa=x||u&&N.find.TAG("*",D&&B.parentNode||B),kc=R+=null==bb?1:Math.random()||.1;W&&(V=B!==H&&B,aa=l);for(;null!=(D=oa[L]);L++){if(u&&D){for(K=0;S=h[K++];)if(S(D,B,A)){I.push(D);break}W&&(R=kc,aa=++l)}r&&((D=!S&&D)&&T--,x&&da.push(D))}T+=L;if(r&&L!==T){for(K=0;S=n[K++];)S(da,ja,B,A);if(x){if(0<T)for(;L--;)da[L]||ja[L]||(ja[L]=jd.call(I));ja=Q(ja)}Ia.apply(I,ja);W&&!x&&0<ja.length&&
		1<T+n.length&&g.uniqueSort(I)}W&&(R=kc,V=bb);return da};return r?e(z):z}function Sa(){}var E,aa,J,V,H,Z,P,X,la,ia,Y,Aa,O="sizzle"+-new Date,ra=a.document,M={},R=0,ma=0,ea=d(),za=d(),fa=d(),pa=typeof b,Ba=[],jd=Ba.pop,Ia=Ba.push,Ja=Ba.slice,sb=Ba.indexOf||function(h){for(var n=0,l=this.length;n<l;n++)if(this[n]===h)return n;return-1};Ba="(?:\\\\.|[\\w-]|[^\\x00-\\xa0])+".replace("w","w#");var lc="\\[[\\x20\\t\\r\\n\\f]*((?:\\\\.|[\\w-]|[^\\x00-\\xa0])+)[\\x20\\t\\r\\n\\f]*(?:([*^$|!~]?=)[\\x20\\t\\r\\n\\f]*(?:(['\"])((?:\\\\.|[^\\\\])*?)\\3|("+
			Ba+")|)|)[\\x20\\t\\r\\n\\f]*\\]",tb=":((?:\\\\.|[\\w-]|[^\\x00-\\xa0])+)(?:\\(((['\"])((?:\\\\.|[^\\\\])*?)\\3|((?:\\\\.|[^\\\\()[\\]]|"+lc.replace(3,8)+")*)|.*)\\)|)",$a=/^[\x20\t\r\n\f]+|((?:^|[^\\])(?:\\.)*)[\x20\t\r\n\f]+$/g,hd=/^[\x20\t\r\n\f]*,[\x20\t\r\n\f]*/,id=/^[\x20\t\r\n\f]*([\x20\t\r\n\f>+~])[\x20\t\r\n\f]*/,kd=new RegExp(tb),ld=new RegExp("^"+Ba+"$"),ab={ID:/^#((?:\\.|[\w-]|[^\x00-\xa0])+)/,CLASS:/^\.((?:\\.|[\w-]|[^\x00-\xa0])+)/,NAME:/^\[name=['"]?((?:\\.|[\w-]|[^\x00-\xa0])+)['"]?\]/,
				TAG:new RegExp("^("+"(?:\\\\.|[\\w-]|[^\\x00-\\xa0])+".replace("w","w*")+")"),ATTR:new RegExp("^"+lc),PSEUDO:new RegExp("^"+tb),CHILD:/^:(only|first|last|nth|nth-last)-(child|of-type)(?:\([\x20\t\r\n\f]*(even|odd|(([+-]|)(\d*)n|)[\x20\t\r\n\f]*(?:([+-]|)[\x20\t\r\n\f]*(\d+)|))[\x20\t\r\n\f]*\)|)/i,needsContext:/^[\x20\t\r\n\f]*[>+~]|:(even|odd|eq|gt|lt|nth|first|last)(?:\([\x20\t\r\n\f]*((?:-\d)?\d*)[\x20\t\r\n\f]*\)|)(?=[^-]|$)/i},rb=/[\x20\t\r\n\f]*[+~]/,ub=/^[^{]+\{\s*\[native code/,fd=/^(?:#([\w-]+)|(\w+)|\.([\w-]+))$/,
			md=/^(?:input|select|textarea|button)$/i,nd=/^h\d$/i,gd=/'|\\/g,od=/=[\x20\t\r\n\f]*([^'"\]]*)[\x20\t\r\n\f]*\]/g,ua=/\\([\da-fA-F]{1,6}[\x20\t\r\n\f]?|.)/g,va=function(h,n){h="0x"+n-65536;return h!==h?n:0>h?String.fromCharCode(h+65536):String.fromCharCode(h>>10|55296,h&1023|56320)};try{Ja.call(ra.documentElement.childNodes,0)[0].nodeType}catch(h){Ja=function(n){for(var l,r=[];l=this[n++];)r.push(l);return r}}var pd=g.isXML=function(h){return(h=h&&(h.ownerDocument||h).documentElement)?"HTML"!==h.nodeName:
			!1};var Ra=g.setDocument=function(h){var n=h?h.ownerDocument||h:ra;if(n===H||9!==n.nodeType||!n.documentElement)return H;H=n;Z=n.documentElement;P=pd(n);M.tagNameNoComments=f(function(l){l.appendChild(n.createComment(""));return!l.getElementsByTagName("*").length});M.attributes=f(function(l){l.innerHTML="<select></select>";l=typeof l.lastChild.getAttribute("multiple");return"boolean"!==l&&"string"!==l});M.getByClassName=f(function(l){l.innerHTML="<div class='hidden e'></div><div class='hidden'></div>";
			if(!l.getElementsByClassName||!l.getElementsByClassName("e").length)return!1;l.lastChild.className="e";return 2===l.getElementsByClassName("e").length});M.getByName=f(function(l){l.id=O+0;l.innerHTML="<a name='"+O+"'></a><div name='"+O+"'></div>";Z.insertBefore(l,Z.firstChild);var r=n.getElementsByName&&n.getElementsByName(O).length===2+n.getElementsByName(O+0).length;M.getIdNotName=!n.getElementById(O);Z.removeChild(l);return r});N.attrHandle=f(function(l){l.innerHTML="<a href='#'></a>";return l.firstChild&&
			typeof l.firstChild.getAttribute!==pa&&"#"===l.firstChild.getAttribute("href")})?{}:{href:function(l){return l.getAttribute("href",2)},type:function(l){return l.getAttribute("type")}};M.getIdNotName?(N.find.ID=function(l,r){if(typeof r.getElementById!==pa&&!P)return(l=r.getElementById(l))&&l.parentNode?[l]:[]},N.filter.ID=function(l){var r=l.replace(ua,va);return function(u){return u.getAttribute("id")===r}}):(N.find.ID=function(l,r){if(typeof r.getElementById!==pa&&!P)return(r=r.getElementById(l))?
			r.id===l||typeof r.getAttributeNode!==pa&&r.getAttributeNode("id").value===l?[r]:b:[]},N.filter.ID=function(l){var r=l.replace(ua,va);return function(u){return(u=typeof u.getAttributeNode!==pa&&u.getAttributeNode("id"))&&u.value===r}});N.find.TAG=M.tagNameNoComments?function(l,r){if(typeof r.getElementsByTagName!==pa)return r.getElementsByTagName(l)}:function(l,r){var u=[],z=0;r=r.getElementsByTagName(l);if("*"===l){for(;l=r[z++];)1===l.nodeType&&u.push(l);return u}return r};N.find.NAME=M.getByName&&
			function(l,r){if(typeof r.getElementsByName!==pa)return r.getElementsByName(name)};N.find.CLASS=M.getByClassName&&function(l,r){if(typeof r.getElementsByClassName!==pa&&!P)return r.getElementsByClassName(l)};la=[];X=[":focus"];if(M.qsa=ub.test(n.querySelectorAll+""))f(function(l){l.innerHTML="<select><option selected=''></option></select>";l.querySelectorAll("[selected]").length||X.push("\\[[\\x20\\t\\r\\n\\f]*(?:checked|disabled|ismap|multiple|readonly|selected|value)");l.querySelectorAll(":checked").length||
		X.push(":checked")}),f(function(l){l.innerHTML="<input type='hidden' i=''/>";l.querySelectorAll("[i^='']").length&&X.push("[*^$]=[\\x20\\t\\r\\n\\f]*(?:\"\"|'')");l.querySelectorAll(":enabled").length||X.push(":enabled",":disabled");l.querySelectorAll("*,:x");X.push(",.*:")});(M.matchesSelector=ub.test((ia=Z.matchesSelector||Z.mozMatchesSelector||Z.webkitMatchesSelector||Z.oMatchesSelector||Z.msMatchesSelector)+""))&&f(function(l){M.disconnectedMatch=ia.call(l,"div");ia.call(l,"[s!='']:x");la.push("!=",
			tb)});X=new RegExp(X.join("|"));la=new RegExp(la.join("|"));Y=ub.test(Z.contains+"")||Z.compareDocumentPosition?function(l,r){var u=9===l.nodeType?l.documentElement:l;r=r&&r.parentNode;return l===r||!!(r&&1===r.nodeType&&(u.contains?u.contains(r):l.compareDocumentPosition&&l.compareDocumentPosition(r)&16))}:function(l,r){if(r)for(;r=r.parentNode;)if(r===l)return!0;return!1};Aa=Z.compareDocumentPosition?function(l,r){var u;return l===r?(J=!0,0):(u=r.compareDocumentPosition&&l.compareDocumentPosition&&
			l.compareDocumentPosition(r))?u&1||l.parentNode&&11===l.parentNode.nodeType?l===n||Y(ra,l)?-1:r===n||Y(ra,r)?1:0:u&4?-1:1:l.compareDocumentPosition?-1:1}:function(l,r){var u=0,z=l.parentNode,x=r.parentNode,B=[l],A=[r];if(l===r)return J=!0,0;if(!z||!x)return l===n?-1:r===n?1:z?-1:x?1:0;if(z===x)return k(l,r);for(;l=l.parentNode;)B.unshift(l);for(l=r;l=l.parentNode;)A.unshift(l);for(;B[u]===A[u];)u++;return u?k(B[u],A[u]):B[u]===ra?-1:A[u]===ra?1:0};J=!1;[0,0].sort(Aa);M.detectDuplicates=J;return H};
		g.matches=function(h,n){return g(h,null,null,n)};g.matchesSelector=function(h,n){(h.ownerDocument||h)!==H&&Ra(h);n=n.replace(od,"='$1']");if(!(!M.matchesSelector||P||la&&la.test(n)||X.test(n)))try{var l=ia.call(h,n);if(l||M.disconnectedMatch||h.document&&11!==h.document.nodeType)return l}catch(r){}return 0<g(n,H,null,[h]).length};g.contains=function(h,n){(h.ownerDocument||h)!==H&&Ra(h);return Y(h,n)};g.attr=function(h,n){var l;(h.ownerDocument||h)!==H&&Ra(h);P||(n=n.toLowerCase());return(l=N.attrHandle[n])?
			l(h):P||M.attributes?h.getAttribute(n):((l=h.getAttributeNode(n))||h.getAttribute(n))&&!0===h[n]?n:l&&l.specified?l.value:null};g.error=function(h){throw Error("Syntax error, unrecognized expression: "+h);};g.uniqueSort=function(h){var n,l=[],r=1,u=0;J=!M.detectDuplicates;h.sort(Aa);if(J){for(;n=h[r];r++)n===h[r-1]&&(u=l.push(r));for(;u--;)h.splice(l[u],1)}return h};var vb=g.getText=function(h){var n="",l=0;var r=h.nodeType;if(!r)for(;r=h[l];l++)n+=vb(r);else if(1===r||9===r||11===r){if("string"===
			typeof h.textContent)return h.textContent;for(h=h.firstChild;h;h=h.nextSibling)n+=vb(h)}else if(3===r||4===r)return h.nodeValue;return n};var N=g.selectors={cacheLength:50,createPseudo:e,match:ab,find:{},relative:{">":{dir:"parentNode",first:!0}," ":{dir:"parentNode"},"+":{dir:"previousSibling",first:!0},"~":{dir:"previousSibling"}},preFilter:{ATTR:function(h){h[1]=h[1].replace(ua,va);h[3]=(h[4]||h[5]||"").replace(ua,va);"~="===h[2]&&(h[3]=" "+h[3]+" ");return h.slice(0,4)},CHILD:function(h){h[1]=
					h[1].toLowerCase();"nth"===h[1].slice(0,3)?(h[3]||g.error(h[0]),h[4]=+(h[4]?h[5]+(h[6]||1):2*("even"===h[3]||"odd"===h[3])),h[5]=+(h[7]+h[8]||"odd"===h[3])):h[3]&&g.error(h[0]);return h},PSEUDO:function(h){var n,l=!h[5]&&h[2];if(ab.CHILD.test(h[0]))return null;h[4]?h[2]=h[4]:l&&kd.test(l)&&(n=v(l,!0))&&(n=l.indexOf(")",l.length-n)-l.length)&&(h[0]=h[0].slice(0,n),h[2]=l.slice(0,n));return h.slice(0,3)}},filter:{TAG:function(h){if("*"===h)return function(){return!0};h=h.replace(ua,va).toLowerCase();
					return function(n){return n.nodeName&&n.nodeName.toLowerCase()===h}},CLASS:function(h){var n=ea[h+" "];return n||(n=new RegExp("(^|[\\x20\\t\\r\\n\\f])"+h+"([\\x20\\t\\r\\n\\f]|$)"),ea(h,function(l){return n.test(l.className||typeof l.getAttribute!==pa&&l.getAttribute("class")||"")}))},ATTR:function(h,n,l){return function(r){r=g.attr(r,h);if(null==r)return"!="===n;if(!n)return!0;r+="";return"="===n?r===l:"!="===n?r!==l:"^="===n?l&&0===r.indexOf(l):"*="===n?l&&-1<r.indexOf(l):"$="===n?l&&r.slice(-l.length)===
					l:"~="===n?-1<(" "+r+" ").indexOf(l):"|="===n?r===l||r.slice(0,l.length+1)===l+"-":!1}},CHILD:function(h,n,l,r,u){var z="nth"!==h.slice(0,3),x="last"!==h.slice(-4),B="of-type"===n;return 1===r&&0===u?function(A){return!!A.parentNode}:function(A,I,D){var K;I=z!==x?"nextSibling":"previousSibling";var S=A.parentNode,ja=B&&A.nodeName.toLowerCase();D=!D&&!B;if(S){if(z){for(;I;){for(K=A;K=K[I];)if(B?K.nodeName.toLowerCase()===ja:1===K.nodeType)return!1;var T=I="only"===h&&!T&&"nextSibling"}return!0}T=[x?
					S.firstChild:S.lastChild];if(x&&D){D=S[O]||(S[O]={});var L=D[h]||[];var da=L[0]===R&&L[1];var W=L[0]===R&&L[2];for(K=da&&S.childNodes[da];K=++da&&K&&K[I]||(W=da=0)||T.pop();)if(1===K.nodeType&&++W&&K===A){D[h]=[R,da,W];break}}else if(D&&(L=(A[O]||(A[O]={}))[h])&&L[0]===R)W=L[1];else for(;(K=++da&&K&&K[I]||(W=da=0)||T.pop())&&((B?K.nodeName.toLowerCase()!==ja:1!==K.nodeType)||!++W||(D&&((K[O]||(K[O]={}))[h]=[R,W]),K!==A)););W-=u;return W===r||0===W%r&&0<=W/r}}},PSEUDO:function(h,n){var l=N.pseudos[h]||
					N.setFilters[h.toLowerCase()]||g.error("unsupported pseudo: "+h);if(l[O])return l(n);if(1<l.length){var r=[h,h,"",n];return N.setFilters.hasOwnProperty(h.toLowerCase())?e(function(u,z){for(var x,B=l(u,n),A=B.length;A--;)x=sb.call(u,B[A]),u[x]=!(z[x]=B[A])}):function(u){return l(u,0,r)}}return l}},pseudos:{not:e(function(h){var n=[],l=[],r=jc(h.replace($a,"$1"));return r[O]?e(function(u,z,x,B){B=r(u,null,B,[]);for(var A=u.length;A--;)if(x=B[A])u[A]=!(z[A]=x)}):function(u,z,x){n[0]=u;r(n,null,x,l);
					return!l.pop()}}),has:e(function(h){return function(n){return 0<g(h,n).length}}),contains:e(function(h){return function(n){return-1<(n.textContent||n.innerText||vb(n)).indexOf(h)}}),lang:e(function(h){ld.test(h||"")||g.error("unsupported lang: "+h);h=h.replace(ua,va).toLowerCase();return function(n){var l;do if(l=P?n.getAttribute("xml:lang")||n.getAttribute("lang"):n.lang)return l=l.toLowerCase(),l===h||0===l.indexOf(h+"-");while((n=n.parentNode)&&1===n.nodeType);return!1}}),target:function(h){var n=
					a.location&&a.location.hash;return n&&n.slice(1)===h.id},root:function(h){return h===Z},focus:function(h){return h===H.activeElement&&(!H.hasFocus||H.hasFocus())&&!!(h.type||h.href||~h.tabIndex)},enabled:function(h){return!1===h.disabled},disabled:function(h){return!0===h.disabled},checked:function(h){var n=h.nodeName.toLowerCase();return"input"===n&&!!h.checked||"option"===n&&!!h.selected},selected:function(h){h.parentNode&&h.parentNode.selectedIndex;return!0===h.selected},empty:function(h){for(h=
																																																																																																																																			 h.firstChild;h;h=h.nextSibling)if("@"<h.nodeName||3===h.nodeType||4===h.nodeType)return!1;return!0},parent:function(h){return!N.pseudos.empty(h)},header:function(h){return nd.test(h.nodeName)},input:function(h){return md.test(h.nodeName)},button:function(h){var n=h.nodeName.toLowerCase();return"input"===n&&"button"===h.type||"button"===n},text:function(h){var n;return"input"===h.nodeName.toLowerCase()&&"text"===h.type&&(null==(n=h.getAttribute("type"))||n.toLowerCase()===h.type)},first:q(function(){return[0]}),
				last:q(function(h,n){return[n-1]}),eq:q(function(h,n,l){return[0>l?l+n:l]}),even:q(function(h,n){for(var l=0;l<n;l+=2)h.push(l);return h}),odd:q(function(h,n){for(var l=1;l<n;l+=2)h.push(l);return h}),lt:q(function(h,n,l){for(n=0>l?l+n:l;0<=--n;)h.push(n);return h}),gt:q(function(h,n,l){for(l=0>l?l+n:l;++l<n;)h.push(l);return h})}};for(E in{radio:!0,checkbox:!0,file:!0,password:!0,image:!0})N.pseudos[E]=m(E);for(E in{submit:!0,reset:!0})N.pseudos[E]=p(E);var jc=g.compile=function(h,n){var l,r=[],
			u=[],z=fa[h+" "];if(!z){n||(n=v(h));for(l=n.length;l--;)z=U(n[l]),z[O]?r.push(z):u.push(z);z=fa(h,ka(u,r))}return z};N.pseudos.nth=N.pseudos.eq;N.filters=Sa.prototype=N.pseudos;N.setFilters=new Sa;Ra();g.attr=c.attr;c.find=g;c.expr=g.selectors;c.expr[":"]=c.expr.pseudos;c.unique=g.uniqueSort;c.text=g.getText;c.isXMLDoc=g.isXML;c.contains=g.contains})(F);var qd=/Until$/,rd=/^(?:parents|prev(?:Until|All))/,Ec=/^.[^:#\[\.,]*$/,mc=c.expr.match.needsContext,sd={children:!0,contents:!0,next:!0,prev:!0};
	c.fn.extend({find:function(a){var b,d=this.length;if("string"!==typeof a){var e=this;return this.pushStack(c(a).filter(function(){for(b=0;b<d;b++)if(c.contains(e[b],this))return!0}))}var f=[];for(b=0;b<d;b++)c.find(a,this[b],f);f=this.pushStack(1<d?c.unique(f):f);f.selector=(this.selector?this.selector+" ":"")+a;return f},has:function(a){var b,d=c(a,this),e=d.length;return this.filter(function(){for(b=0;b<e;b++)if(c.contains(this,d[b]))return!0})},not:function(a){return this.pushStack(Ib(this,a,!1))},
		filter:function(a){return this.pushStack(Ib(this,a,!0))},is:function(a){return!!a&&("string"===typeof a?mc.test(a)?0<=c(a,this.context).index(this[0]):0<c.filter(a,this).length:0<this.filter(a).length)},closest:function(a,b){for(var d,e=0,f=this.length,g=[],k=mc.test(a)||"string"!==typeof a?c(a,b||this.context):0;e<f;e++)for(d=this[e];d&&d.ownerDocument&&d!==b&&11!==d.nodeType;){if(k?-1<k.index(d):c.find.matchesSelector(d,a)){g.push(d);break}d=d.parentNode}return this.pushStack(1<g.length?c.unique(g):
			g)},index:function(a){return a?"string"===typeof a?c.inArray(this[0],c(a)):c.inArray(a.jquery?a[0]:a,this):this[0]&&this[0].parentNode?this.first().prevAll().length:-1},add:function(a,b){a="string"===typeof a?c(a,b):c.makeArray(a&&a.nodeType?[a]:a);a=c.merge(this.get(),a);return this.pushStack(c.unique(a))},addBack:function(a){return this.add(null==a?this.prevObject:this.prevObject.filter(a))}});c.fn.andSelf=c.fn.addBack;c.each({parent:function(a){return(a=a.parentNode)&&11!==a.nodeType?a:null},parents:function(a){return c.dir(a,
			"parentNode")},parentsUntil:function(a,b,d){return c.dir(a,"parentNode",d)},next:function(a){return Hb(a,"nextSibling")},prev:function(a){return Hb(a,"previousSibling")},nextAll:function(a){return c.dir(a,"nextSibling")},prevAll:function(a){return c.dir(a,"previousSibling")},nextUntil:function(a,b,d){return c.dir(a,"nextSibling",d)},prevUntil:function(a,b,d){return c.dir(a,"previousSibling",d)},siblings:function(a){return c.sibling((a.parentNode||{}).firstChild,a)},children:function(a){return c.sibling(a.firstChild)},
		contents:function(a){return c.nodeName(a,"iframe")?a.contentDocument||a.contentWindow.document:c.merge([],a.childNodes)}},function(a,b){c.fn[a]=function(d,e){var f=c.map(this,b,d);qd.test(a)||(e=d);e&&"string"===typeof e&&(f=c.filter(e,f));f=1<this.length&&!sd[a]?c.unique(f):f;1<this.length&&rd.test(a)&&(f=f.reverse());return this.pushStack(f)}});c.extend({filter:function(a,b,d){d&&(a=":not("+a+")");return 1===b.length?c.find.matchesSelector(b[0],a)?[b[0]]:[]:c.find.matches(a,b)},dir:function(a,b,
																																																																																																																														  d){var e=[];for(a=a[b];a&&9!==a.nodeType&&(d===y||1!==a.nodeType||!c(a).is(d));)1===a.nodeType&&e.push(a),a=a[b];return e},sibling:function(a,b){for(var d=[];a;a=a.nextSibling)1===a.nodeType&&a!==b&&d.push(a);return d}});var Kb="abbr|article|aside|audio|bdi|canvas|data|datalist|details|figcaption|figure|footer|header|hgroup|mark|meter|nav|output|progress|section|summary|time|video",td=/ jQuery\d+="(?:null|\d+)"/g,nc=new RegExp("<(?:"+Kb+")[\\s/>]","i"),wb=/^\s+/,oc=/<(?!area|br|col|embed|hr|img|input|link|meta|param)(([\w:]+)[^>]*)\/>/gi,
		pc=/<([\w:]+)/,qc=/<tbody/i,ud=/<|&#?\w+;/,vd=/<(?:script|style|link)/i,hb=/^(?:checkbox|radio)$/i,wd=/checked\s*(?:[^=]|=\s*.checked.)/i,rc=/^$|\/(?:java|ecma)script/i,Gc=/^true\/(.*)/,xd=/^\s*<!(?:\[CDATA\[|--)|(?:\]\]|--)>\s*$/g,na={option:[1,"<select multiple='multiple'>","</select>"],legend:[1,"<fieldset>","</fieldset>"],area:[1,"<map>","</map>"],param:[1,"<object>","</object>"],thead:[1,"<table>","</table>"],tr:[2,"<table><tbody>","</tbody></table>"],col:[2,"<table><tbody></tbody><colgroup>",
				"</colgroup></table>"],td:[3,"<table><tbody><tr>","</tr></tbody></table>"],_default:c.support.htmlSerialize?[0,"",""]:[1,"X<div>","</div>"]},xb=Jb(C).appendChild(C.createElement("div"));na.optgroup=na.option;na.tbody=na.tfoot=na.colgroup=na.caption=na.thead;na.th=na.td;c.fn.extend({text:function(a){return c.access(this,function(b){return b===y?c.text(this):this.empty().append((this[0]&&this[0].ownerDocument||C).createTextNode(b))},null,a,arguments.length)},wrapAll:function(a){if(c.isFunction(a))return this.each(function(d){c(this).wrapAll(a.call(this,
			d))});if(this[0]){var b=c(a,this[0].ownerDocument).eq(0).clone(!0);this[0].parentNode&&b.insertBefore(this[0]);b.map(function(){for(var d=this;d.firstChild&&1===d.firstChild.nodeType;)d=d.firstChild;return d}).append(this)}return this},wrapInner:function(a){return c.isFunction(a)?this.each(function(b){c(this).wrapInner(a.call(this,b))}):this.each(function(){var b=c(this),d=b.contents();d.length?d.wrapAll(a):b.append(a)})},wrap:function(a){var b=c.isFunction(a);return this.each(function(d){c(this).wrapAll(b?
			a.call(this,d):a)})},unwrap:function(){return this.parent().each(function(){c.nodeName(this,"body")||c(this).replaceWith(this.childNodes)}).end()},append:function(){return this.domManip(arguments,!0,function(a){1!==this.nodeType&&11!==this.nodeType&&9!==this.nodeType||this.appendChild(a)})},prepend:function(){return this.domManip(arguments,!0,function(a){1!==this.nodeType&&11!==this.nodeType&&9!==this.nodeType||this.insertBefore(a,this.firstChild)})},before:function(){return this.domManip(arguments,
			!1,function(a){this.parentNode&&this.parentNode.insertBefore(a,this)})},after:function(){return this.domManip(arguments,!1,function(a){this.parentNode&&this.parentNode.insertBefore(a,this.nextSibling)})},remove:function(a,b){for(var d,e=0;null!=(d=this[e]);e++)if(!a||0<c.filter(a,[d]).length)b||1!==d.nodeType||c.cleanData(ca(d)),d.parentNode&&(b&&c.contains(d.ownerDocument,d)&&gb(ca(d,"script")),d.parentNode.removeChild(d));return this},empty:function(){for(var a,b=0;null!=(a=this[b]);b++){for(1===
																																																																																																																															   a.nodeType&&c.cleanData(ca(a,!1));a.firstChild;)a.removeChild(a.firstChild);a.options&&c.nodeName(a,"select")&&(a.options.length=0)}return this},clone:function(a,b){a=null==a?!1:a;b=null==b?a:b;return this.map(function(){return c.clone(this,a,b)})},html:function(a){return c.access(this,function(b){var d=this[0]||{},e=0,f=this.length;if(b===y)return 1===d.nodeType?d.innerHTML.replace(td,""):y;if(!("string"!==typeof b||vd.test(b)||!c.support.htmlSerialize&&nc.test(b)||!c.support.leadingWhitespace&&
			wb.test(b)||na[(pc.exec(b)||["",""])[1].toLowerCase()])){b=b.replace(oc,"<$1></$2>");try{for(;e<f;e++)d=this[e]||{},1===d.nodeType&&(c.cleanData(ca(d,!1)),d.innerHTML=b);d=0}catch(g){}}d&&this.empty().append(b)},null,a,arguments.length)},replaceWith:function(a){c.isFunction(a)||"string"===typeof a||(a=c(a).not(this).detach());return this.domManip([a],!0,function(b){var d=this.nextSibling,e=this.parentNode;e&&(c(this).remove(),e.insertBefore(b,d))})},detach:function(a){return this.remove(a,!0)},domManip:function(a,
																																																																																																																																				 b,d){a=cc.apply([],a);var e,f=0,g=this.length,k=this,m=g-1,p=a[0],q=c.isFunction(p);if(q||!(1>=g||"string"!==typeof p||c.support.checkClone)&&wd.test(p))return this.each(function(G){var Q=k.eq(G);q&&(a[0]=p.call(this,G,b?Q.html():y));Q.domManip(a,b,d)});if(g){var v=c.buildFragment(a,this[0].ownerDocument,!1,this);var t=v.firstChild;1===v.childNodes.length&&(v=t);if(t){b=b&&c.nodeName(t,"tr");var w=c.map(ca(v,"script"),Lb);for(e=w.length;f<g;f++)t=v,f!==m&&(t=c.clone(t,!0,!0),e&&c.merge(w,ca(t,"script"))),
			d.call(b&&c.nodeName(this[f],"table")?Fc(this[f],"tbody"):this[f],t,f);if(e)for(v=w[w.length-1].ownerDocument,c.map(w,Mb),f=0;f<e;f++)t=w[f],rc.test(t.type||"")&&!c._data(t,"globalEval")&&c.contains(v,t)&&(t.src?c.ajax({url:t.src,type:"GET",dataType:"script",async:!1,global:!1,"throws":!0}):c.globalEval((t.text||t.textContent||t.innerHTML||"").replace(xd,"")));v=t=null}}return this}});c.each({appendTo:"append",prependTo:"prepend",insertBefore:"before",insertAfter:"after",replaceAll:"replaceWith"},
		function(a,b){c.fn[a]=function(d){for(var e=0,f=[],g=c(d),k=g.length-1;e<=k;e++)d=e===k?this:this.clone(!0),c(g[e])[b](d),lb.apply(f,d.get());return this.pushStack(f)}});c.extend({clone:function(a,b,d){var e,f,g=c.contains(a.ownerDocument,a);if(c.support.html5Clone||c.isXMLDoc(a)||!nc.test("<"+a.nodeName+">"))var k=a.cloneNode(!0);else xb.innerHTML=a.outerHTML,xb.removeChild(k=xb.firstChild);if(!(c.support.noCloneEvent&&c.support.noCloneChecked||1!==a.nodeType&&11!==a.nodeType||c.isXMLDoc(a))){var m=
			ca(k);var p=ca(a);for(f=0;null!=(e=p[f]);++f)if(m[f]){var q=void 0,v=e,t=m[f];if(1===t.nodeType){var w=t.nodeName.toLowerCase();if(!c.support.noCloneEvent&&t[c.expando]){e=c._data(t);for(q in e.events)c.removeEvent(t,q,e.handle);t.removeAttribute(c.expando)}if("script"===w&&t.text!==v.text)Lb(t).text=v.text,Mb(t);else if("object"===w)t.parentNode&&(t.outerHTML=v.outerHTML),c.support.html5Clone&&v.innerHTML&&!c.trim(t.innerHTML)&&(t.innerHTML=v.innerHTML);else if("input"===w&&hb.test(v.type))t.defaultChecked=
			t.checked=v.checked,t.value!==v.value&&(t.value=v.value);else if("option"===w)t.defaultSelected=t.selected=v.defaultSelected;else if("input"===w||"textarea"===w)t.defaultValue=v.defaultValue}}}if(b)if(d)for(p=p||ca(a),m=m||ca(k),f=0;null!=(e=p[f]);f++)Nb(e,m[f]);else Nb(a,k);m=ca(k,"script");0<m.length&&gb(m,!g&&ca(a,"script"));return k},buildFragment:function(a,b,d,e){for(var f,g,k,m,p,q,v=a.length,t=Jb(b),w=[],G=0;G<v;G++)if((g=a[G])||0===g)if("object"===c.type(g))c.merge(w,g.nodeType?[g]:g);else if(ud.test(g)){k=
			k||t.appendChild(b.createElement("div"));m=(pc.exec(g)||["",""])[1].toLowerCase();q=na[m]||na._default;k.innerHTML=q[1]+g.replace(oc,"<$1></$2>")+q[2];for(f=q[0];f--;)k=k.lastChild;!c.support.leadingWhitespace&&wb.test(g)&&w.push(b.createTextNode(wb.exec(g)[0]));if(!c.support.tbody)for(f=(g="table"!==m||qc.test(g)?"<table>"!==q[1]||qc.test(g)?0:k:k.firstChild)&&g.childNodes.length;f--;)c.nodeName(p=g.childNodes[f],"tbody")&&!p.childNodes.length&&g.removeChild(p);c.merge(w,k.childNodes);for(k.textContent=
																																																																																																																															   "";k.firstChild;)k.removeChild(k.firstChild);k=t.lastChild}else w.push(b.createTextNode(g));k&&t.removeChild(k);c.support.appendChecked||c.grep(ca(w,"input"),Hc);for(G=0;g=w[G++];)if(!e||-1===c.inArray(g,e))if(a=c.contains(g.ownerDocument,g),k=ca(t.appendChild(g),"script"),a&&gb(k),d)for(f=0;g=k[f++];)rc.test(g.type||"")&&d.push(g);return t},cleanData:function(a,b){for(var d,e,f,g,k=0,m=c.expando,p=c.cache,q=c.support.deleteExpando,v=c.event.special;null!=(d=a[k]);k++)if(b||c.acceptData(d))if(g=(f=
			d[m])&&p[f]){if(g.events)for(e in g.events)v[e]?c.event.remove(d,e):c.removeEvent(d,e,g.handle);p[f]&&(delete p[f],q?delete d[m]:typeof d.removeAttribute!==qa?d.removeAttribute(m):d[m]=null,Da.push(f))}}});var Na,yb=/alpha\([^)]*\)/i,yd=/opacity\s*=\s*([^)]*)/,zd=/^(top|right|bottom|left)$/,Ad=/^(none|table(?!-c[ea]).+)/,sc=/^margin/,Ic=new RegExp("^("+Za+")(.*)$","i"),Ua=new RegExp("^("+Za+")(?!px)[a-z%]+$","i"),Bd=new RegExp("^([+-])=("+Za+")","i"),Vb={BODY:"block"},Cd={position:"absolute",visibility:"hidden",
		display:"block"},tc={letterSpacing:0,fontWeight:400},wa=["Top","Right","Bottom","Left"],Pb=["Webkit","O","Moz","ms"];c.fn.extend({css:function(a,b){return c.access(this,function(d,e,f){var g={},k=0;if(c.isArray(e)){var m=Fa(d);for(f=e.length;k<f;k++)g[e[k]]=c.css(d,e[k],!1,m);return g}return f!==y?c.style(d,e,f):c.css(d,e)},a,b,1<arguments.length)},show:function(){return Qb(this,!0)},hide:function(){return Qb(this)},toggle:function(a){var b="boolean"===typeof a;return this.each(function(){(b?a:Ma(this))?
			c(this).show():c(this).hide()})}});c.extend({cssHooks:{opacity:{get:function(a,b){if(b)return a=Ga(a,"opacity"),""===a?"1":a}}},cssNumber:{columnCount:!0,fillOpacity:!0,fontWeight:!0,lineHeight:!0,opacity:!0,orphans:!0,widows:!0,zIndex:!0,zoom:!0},cssProps:{"float":c.support.cssFloat?"cssFloat":"styleFloat"},style:function(a,b,d,e){if(a&&3!==a.nodeType&&8!==a.nodeType&&a.style){var f,g=c.camelCase(b),k=a.style;b=c.cssProps[g]||(c.cssProps[g]=Ob(k,g));var m=c.cssHooks[b]||c.cssHooks[g];if(d!==y){var p=
			typeof d;"string"===p&&(f=Bd.exec(d))&&(d=(f[1]+1)*f[2]+parseFloat(c.css(a,b)),p="number");if(!(null==d||"number"===p&&isNaN(d)||("number"!==p||c.cssNumber[g]||(d+="px"),c.support.clearCloneStyle||""!==d||0!==b.indexOf("background")||(k[b]="inherit"),m&&"set"in m&&(d=m.set(a,d,e))===y)))try{k[b]=d}catch(q){}}else return m&&"get"in m&&(f=m.get(a,!1,e))!==y?f:k[b]}},css:function(a,b,d,e){var f;var g=c.camelCase(b);b=c.cssProps[g]||(c.cssProps[g]=Ob(a.style,g));(g=c.cssHooks[b]||c.cssHooks[g])&&"get"in
		g&&(f=g.get(a,!0,d));f===y&&(f=Ga(a,b,e));"normal"===f&&b in tc&&(f=tc[b]);return""===d||d?(a=parseFloat(f),!0===d||c.isNumeric(a)?a||0:f):f},swap:function(a,b,d,e){var f,g={};for(f in b)g[f]=a.style[f],a.style[f]=b[f];d=d.apply(a,e||[]);for(f in b)a.style[f]=g[f];return d}});if(F.getComputedStyle){var Fa=function(a){return F.getComputedStyle(a,null)};var Ga=function(a,b,d){var e=(d=d||Fa(a))?d.getPropertyValue(b)||d[b]:y,f=a.style;if(d&&(""!==e||c.contains(a.ownerDocument,a)||(e=c.style(a,b)),Ua.test(e)&&
	sc.test(b))){a=f.width;b=f.minWidth;var g=f.maxWidth;f.minWidth=f.maxWidth=f.width=e;e=d.width;f.width=a;f.minWidth=b;f.maxWidth=g}return e}}else C.documentElement.currentStyle&&(Fa=function(a){return a.currentStyle},Ga=function(a,b,d){var e,f,g=(d=d||Fa(a))?d[b]:y,k=a.style;null==g&&k&&k[b]&&(g=k[b]);if(Ua.test(g)&&!zd.test(b)){d=k.left;if(f=(e=a.runtimeStyle)&&e.left)e.left=a.currentStyle.left;k.left="fontSize"===b?"1em":g;g=k.pixelLeft+"px";k.left=d;f&&(e.left=f)}return""===g?"auto":g});c.each(["height",
		"width"],function(a,b){c.cssHooks[b]={get:function(d,e,f){if(e)return 0===d.offsetWidth&&Ad.test(c.css(d,"display"))?c.swap(d,Cd,function(){return Ub(d,b,f)}):Ub(d,b,f)},set:function(d,e,f){var g=f&&Fa(d);return Sb(d,e,f?Tb(d,b,f,c.support.boxSizing&&"border-box"===c.css(d,"boxSizing",!1,g),g):0)}}});c.support.opacity||(c.cssHooks.opacity={get:function(a,b){return yd.test((b&&a.currentStyle?a.currentStyle.filter:a.style.filter)||"")?.01*parseFloat(RegExp.$1)+"":b?"1":""},set:function(a,b){var d=a.style;
			a=a.currentStyle;var e=c.isNumeric(b)?"alpha(opacity="+100*b+")":"",f=a&&a.filter||d.filter||"";d.zoom=1;if((1<=b||""===b)&&""===c.trim(f.replace(yb,""))&&d.removeAttribute&&(d.removeAttribute("filter"),""===b||a&&!a.filter))return;d.filter=yb.test(f)?f.replace(yb,e):f+" "+e}});c(function(){c.support.reliableMarginRight||(c.cssHooks.marginRight={get:function(a,b){if(b)return c.swap(a,{display:"inline-block"},Ga,[a,"marginRight"])}});!c.support.pixelPosition&&c.fn.position&&c.each(["top","left"],function(a,
																																																																																																																																		 b){c.cssHooks[b]={get:function(d,e){if(e)return e=Ga(d,b),Ua.test(e)?c(d).position()[b]+"px":e}}})});c.expr&&c.expr.filters&&(c.expr.filters.hidden=function(a){return 0>=a.offsetWidth&&0>=a.offsetHeight||!c.support.reliableHiddenOffsets&&"none"===(a.style&&a.style.display||c.css(a,"display"))},c.expr.filters.visible=function(a){return!c.expr.filters.hidden(a)});c.each({margin:"",padding:"",border:"Width"},function(a,b){c.cssHooks[a+b]={expand:function(d){var e=0,f={};for(d="string"===typeof d?d.split(" "):
			[d];4>e;e++)f[a+wa[e]+b]=d[e]||d[e-2]||d[0];return f}};sc.test(a)||(c.cssHooks[a+b].set=Sb)});var Dd=/%20/g,Jc=/\[\]$/,uc=/\r?\n/g,Ed=/^(?:submit|button|image|reset|file)$/i,Fd=/^(?:input|select|textarea|keygen)/i;c.fn.extend({serialize:function(){return c.param(this.serializeArray())},serializeArray:function(){return this.map(function(){var a=c.prop(this,"elements");return a?c.makeArray(a):this}).filter(function(){var a=this.type;return this.name&&!c(this).is(":disabled")&&Fd.test(this.nodeName)&&
			!Ed.test(a)&&(this.checked||!hb.test(a))}).map(function(a,b){a=c(this).val();return null==a?null:c.isArray(a)?c.map(a,function(d){return{name:b.name,value:d.replace(uc,"\r\n")}}):{name:b.name,value:a.replace(uc,"\r\n")}}).get()}});c.param=function(a,b){var d,e=[],f=function(g,k){k=c.isFunction(k)?k():null==k?"":k;e[e.length]=encodeURIComponent(g)+"="+encodeURIComponent(k)};b===y&&(b=c.ajaxSettings&&c.ajaxSettings.traditional);if(c.isArray(a)||a.jquery&&!c.isPlainObject(a))c.each(a,function(){f(this.name,
		this.value)});else for(d in a)ib(d,a[d],b,f);return e.join("&").replace(Dd,"+")};c.each("blur focus focusin focusout load resize scroll unload click dblclick mousedown mouseup mousemove mouseover mouseout mouseenter mouseleave change select submit keydown keypress keyup error contextmenu".split(" "),function(a,b){c.fn[b]=function(d,e){return 0<arguments.length?this.on(b,null,d,e):this.trigger(b)}});c.fn.hover=function(a,b){return this.mouseenter(a).mouseleave(b||a)};var zb=c.now(),Ab=/\?/,Gd=/#.*$/,
		vc=/([?&])_=[^&]*/,Hd=/^(.*?):[ \t]*([^\r\n]*)\r?$/mg,Id=/^(?:GET|HEAD)$/,Jd=/^\/\//,wc=/^([\w.+-]+:)(?:\/\/([^\/?#:]*)(?::(\d+)|)|)/,xc=c.fn.load,yc={},jb={},zc="*/".concat("*");try{var Ca=Mc.href}catch(a){Ca=C.createElement("a"),Ca.href="",Ca=Ca.href}var Ka=wc.exec(Ca.toLowerCase())||[];c.fn.load=function(a,b,d){if("string"!==typeof a&&xc)return xc.apply(this,arguments);var e,f,g=this,k=a.indexOf(" ");if(0<=k){var m=a.slice(k,a.length);a=a.slice(0,k)}c.isFunction(b)?(d=b,b=y):b&&"object"===typeof b&&
		(f="POST");0<g.length&&c.ajax({url:a,type:f,dataType:"html",data:b}).done(function(p){e=arguments;g.html(m?c("<div>").append(c.parseHTML(p)).find(m):p)}).complete(d&&function(p,q){g.each(d,e||[p.responseText,q,p])});return this};c.each("ajaxStart ajaxStop ajaxComplete ajaxError ajaxSuccess ajaxSend".split(" "),function(a,b){c.fn[b]=function(d){return this.on(b,d)}});c.each(["get","post"],function(a,b){c[b]=function(d,e,f,g){c.isFunction(e)&&(g=g||f,f=e,e=y);return c.ajax({url:d,type:b,dataType:g,
		data:e,success:f})}});c.extend({active:0,lastModified:{},etag:{},ajaxSettings:{url:Ca,type:"GET",isLocal:/^(?:about|app|app-storage|.+-extension|file|res|widget):$/.test(Ka[1]),global:!0,processData:!0,async:!0,contentType:"application/x-www-form-urlencoded; charset=UTF-8",accepts:{"*":zc,text:"text/plain",html:"text/html",xml:"application/xml, text/xml",json:"application/json, text/javascript"},contents:{xml:/xml/,html:/html/,json:/json/},responseFields:{xml:"responseXML",text:"responseText"},converters:{"* text":F.String,
				"text html":!0,"text json":c.parseJSON,"text xml":c.parseXML},flatOptions:{url:!0,context:!0}},ajaxSetup:function(a,b){return b?kb(kb(a,c.ajaxSettings),b):kb(c.ajaxSettings,a)},ajaxPrefilter:Xb(yc),ajaxTransport:Xb(jb),ajax:function(a,b){function d(J,V,H,Z){var P=V;if(2!==ka){ka=2;g&&clearTimeout(g);m=y;f=Z||"";E.readyState=0<J?4:0;if(H){var X=q;Z=E;var la,ia,Y,Aa=X.contents,O=X.dataTypes,ra=X.responseFields;for(Y in ra)Y in H&&(Z[ra[Y]]=H[Y]);for(;"*"===O[0];)O.shift(),ia===y&&(ia=X.mimeType||Z.getResponseHeader("Content-Type"));
			if(ia)for(Y in Aa)if(Aa[Y]&&Aa[Y].test(ia)){O.unshift(Y);break}if(O[0]in H)var M=O[0];else{for(Y in H){if(!O[0]||X.converters[Y+" "+O[0]]){M=Y;break}la||(la=Y)}M=M||la}M?(M!==O[0]&&O.unshift(M),X=H[M]):X=void 0}if(200<=J&&300>J||304===J)if(q.ifModified&&((H=E.getResponseHeader("Last-Modified"))&&(c.lastModified[aa]=H),(H=E.getResponseHeader("etag"))&&(c.etag[aa]=H)),204===J){var R=!0;P="nocontent"}else if(304===J)R=!0,P="notmodified";else{a:{var ma=q;var ea=X;var za;P={};la=0;ia=ma.dataTypes.slice();
			M=ia[0];ma.dataFilter&&(ea=ma.dataFilter(ea,ma.dataType));if(ia[1])for(fa in ma.converters)P[fa.toLowerCase()]=ma.converters[fa];for(;H=ia[++la];)if("*"!==H){if("*"!==M&&M!==H){var fa=P[M+" "+H]||P["* "+H];if(!fa)for(za in P)if(R=za.split(" "),R[1]===H&&(fa=P[M+" "+R[0]]||P["* "+R[0]])){!0===fa?fa=P[za]:!0!==P[za]&&(H=R[0],ia.splice(la--,0,H));break}if(!0!==fa)if(fa&&ma["throws"])ea=fa(ea);else try{ea=fa(ea)}catch(pa){R={state:"parsererror",error:fa?pa:"No conversion from "+M+" to "+H};break a}}M=
				H}R={state:"success",data:ea}}P=R.state;ma=R.data;ea=R.error;R=!ea}else if(ea=P,J||!P)P="error",0>J&&(J=0);E.status=J;E.statusText=(V||P)+"";R?w.resolveWith(v,[ma,P,E]):w.rejectWith(v,[E,P,ea]);E.statusCode(Q);Q=y;k&&t.trigger(R?"ajaxSuccess":"ajaxError",[E,q,R?ma:ea]);G.fireWith(v,[E,P]);k&&(t.trigger("ajaxComplete",[E,q]),--c.active||c.event.trigger("ajaxStop"))}}"object"===typeof a&&(b=a,a=y);b=b||{};var e,f,g,k,m,p,q=c.ajaxSetup({},b),v=q.context||q,t=q.context&&(v.nodeType||v.jquery)?c(v):c.event,
			w=c.Deferred(),G=c.Callbacks("once memory"),Q=q.statusCode||{},ba={},U={},ka=0,Sa="canceled",E={readyState:0,getResponseHeader:function(J){var V;if(2===ka){if(!p)for(p={};V=Hd.exec(f);)p[V[1].toLowerCase()]=V[2];V=p[J.toLowerCase()]}return null==V?null:V},getAllResponseHeaders:function(){return 2===ka?f:null},setRequestHeader:function(J,V){var H=J.toLowerCase();ka||(J=U[H]=U[H]||J,ba[J]=V);return this},overrideMimeType:function(J){ka||(q.mimeType=J);return this},statusCode:function(J){var V;if(J)if(2>
					ka)for(V in J)Q[V]=[Q[V],J[V]];else E.always(J[E.status]);return this},abort:function(J){J=J||Sa;m&&m.abort(J);d(0,J);return this}};w.promise(E).complete=G.add;E.success=E.done;E.error=E.fail;q.url=((a||q.url||Ca)+"").replace(Gd,"").replace(Jd,Ka[1]+"//");q.type=b.method||b.type||q.method||q.type;q.dataTypes=c.trim(q.dataType||"*").toLowerCase().match(sa)||[""];null==q.crossDomain&&(a=wc.exec(q.url.toLowerCase()),q.crossDomain=!(!a||a[1]===Ka[1]&&a[2]===Ka[2]&&(a[3]||("http:"===a[1]?80:443))==(Ka[3]||
			("http:"===Ka[1]?80:443))));q.data&&q.processData&&"string"!==typeof q.data&&(q.data=c.param(q.data,q.traditional));Yb(yc,q,b,E);if(2===ka)return E;(k=q.global)&&0===c.active++&&c.event.trigger("ajaxStart");q.type=q.type.toUpperCase();q.hasContent=!Id.test(q.type);var aa=q.url;q.hasContent||(q.data&&(aa=q.url+=(Ab.test(aa)?"&":"?")+q.data,delete q.data),!1===q.cache&&(q.url=vc.test(aa)?aa.replace(vc,"$1_="+zb++):aa+(Ab.test(aa)?"&":"?")+"_="+zb++));q.ifModified&&(c.lastModified[aa]&&E.setRequestHeader("If-Modified-Since",
			c.lastModified[aa]),c.etag[aa]&&E.setRequestHeader("If-None-Match",c.etag[aa]));(q.data&&q.hasContent&&!1!==q.contentType||b.contentType)&&E.setRequestHeader("Content-Type",q.contentType);E.setRequestHeader("Accept",q.dataTypes[0]&&q.accepts[q.dataTypes[0]]?q.accepts[q.dataTypes[0]]+("*"!==q.dataTypes[0]?", "+zc+"; q=0.01":""):q.accepts["*"]);for(e in q.headers)E.setRequestHeader(e,q.headers[e]);if(q.beforeSend&&(!1===q.beforeSend.call(v,E,q)||2===ka))return E.abort();Sa="abort";for(e in{success:1,
			error:1,complete:1})E[e](q[e]);if(m=Yb(jb,q,b,E)){E.readyState=1;k&&t.trigger("ajaxSend",[E,q]);q.async&&0<q.timeout&&(g=setTimeout(function(){E.abort("timeout")},q.timeout));try{ka=1,m.send(ba,d)}catch(J){if(2>ka)d(-1,J);else throw J;}}else d(-1,"No Transport");return E},getScript:function(a,b){return c.get(a,y,b,"script")},getJSON:function(a,b,d){return c.get(a,b,d,"json")}});c.ajaxSetup({accepts:{script:"text/javascript, application/javascript, application/ecmascript, application/x-ecmascript"},
		contents:{script:/(?:java|ecma)script/},converters:{"text script":function(a){c.globalEval(a);return a}}});c.ajaxPrefilter("script",function(a){a.cache===y&&(a.cache=!1);a.crossDomain&&(a.type="GET",a.global=!1)});c.ajaxTransport("script",function(a){if(a.crossDomain){var b,d=C.head||c("head")[0]||C.documentElement;return{send:function(e,f){b=C.createElement("script");b.async=!0;a.scriptCharset&&(b.charset=a.scriptCharset);b.src=a.url;b.onload=b.onreadystatechange=function(g,k){if(k||!b.readyState||
			/loaded|complete/.test(b.readyState))b.onload=b.onreadystatechange=null,b.parentNode&&b.parentNode.removeChild(b),b=null,k||f(200,"success")};d.insertBefore(b,d.firstChild)},abort:function(){if(b)b.onload(y,!0)}}}});var Ac=[],Bb=/(=)\?(?=&|$)|\?\?/;c.ajaxSetup({jsonp:"callback",jsonpCallback:function(){var a=Ac.pop()||c.expando+"_"+zb++;this[a]=!0;return a}});c.ajaxPrefilter("json jsonp",function(a,b,d){var e,f=!1!==a.jsonp&&(Bb.test(a.url)?"url":"string"===typeof a.data&&!(a.contentType||"").indexOf("application/x-www-form-urlencoded")&&
		Bb.test(a.data)&&"data");if(f||"jsonp"===a.dataTypes[0]){var g=a.jsonpCallback=c.isFunction(a.jsonpCallback)?a.jsonpCallback():a.jsonpCallback;f?a[f]=a[f].replace(Bb,"$1"+g):!1!==a.jsonp&&(a.url+=(Ab.test(a.url)?"&":"?")+a.jsonp+"="+g);a.converters["script json"]=function(){e||c.error(g+" was not called");return e[0]};a.dataTypes[0]="json";var k=F[g];F[g]=function(){e=arguments};d.always(function(){F[g]=k;a[g]&&(a.jsonpCallback=b.jsonpCallback,Ac.push(g));e&&c.isFunction(k)&&k(e[0]);e=k=y});return"script"}});
	var La,Kd=0,Cb=F.ActiveXObject&&function(){for(var a in La)La[a](y,!0)};c.ajaxSettings.xhr=F.ActiveXObject?function(){var a;if(!(a=!this.isLocal&&Zb()))a:{try{a=new F.ActiveXObject("Microsoft.XMLHTTP");break a}catch(b){}a=void 0}return a}:Zb;var cb=c.ajaxSettings.xhr();c.support.cors=!!cb&&"withCredentials"in cb;(cb=c.support.ajax=!!cb)&&c.ajaxTransport(function(a){if(!a.crossDomain||c.support.cors){var b;return{send:function(d,e){var f,g=a.xhr();a.username?g.open(a.type,a.url,a.async,a.username,
			a.password):g.open(a.type,a.url,a.async);if(a.xhrFields)for(f in a.xhrFields)g[f]=a.xhrFields[f];a.mimeType&&g.overrideMimeType&&g.overrideMimeType(a.mimeType);a.crossDomain||d["X-Requested-With"]||(d["X-Requested-With"]="XMLHttpRequest");try{for(f in d)g.setRequestHeader(f,d[f])}catch(m){}g.send(a.hasContent&&a.data||null);b=function(m,p){try{if(b&&(p||4===g.readyState))if(b=y,k&&(g.onreadystatechange=c.noop,Cb&&delete La[k]),p)4!==g.readyState&&g.abort();else{var q={};var v=g.status;var t=g.getAllResponseHeaders();
			"string"===typeof g.responseText&&(q.text=g.responseText);try{var w=g.statusText}catch(G){w=""}v||!a.isLocal||a.crossDomain?1223===v&&(v=204):v=q.text?200:404}}catch(G){p||e(-1,G)}q&&e(v,w,q,t)};if(a.async)if(4===g.readyState)setTimeout(b);else{var k=++Kd;Cb&&(La||(La={},c(F).unload(Cb)),La[k]=b);g.onreadystatechange=b}else b()},abort:function(){b&&b(y,!0)}}}});var Ha,db,Ld=/^(?:toggle|show|hide)$/,Md=new RegExp("^(?:([+-])=|)("+Za+")([a-z%]*)$","i"),Nd=/queueHooks$/,Va=[function(a,b,d){var e,f=this,
		g=a.style,k={},m=[],p=a.nodeType&&Ma(a);if(!d.queue){var q=c._queueHooks(a,"fx");if(null==q.unqueued){q.unqueued=0;var v=q.empty.fire;q.empty.fire=function(){q.unqueued||v()}}q.unqueued++;f.always(function(){f.always(function(){q.unqueued--;c.queue(a,"fx").length||q.empty.fire()})})}1===a.nodeType&&("height"in b||"width"in b)&&(d.overflow=[g.overflow,g.overflowX,g.overflowY],"inline"===c.css(a,"display")&&"none"===c.css(a,"float")&&(c.support.inlineBlockNeedsLayout&&"inline"!==Rb(a.nodeName)?g.zoom=
		1:g.display="inline-block"));d.overflow&&(g.overflow="hidden",c.support.shrinkWrapBlocks||f.always(function(){g.overflow=d.overflow[0];g.overflowX=d.overflow[1];g.overflowY=d.overflow[2]}));for(e in b){var t=b[e];if(Ld.exec(t)){delete b[e];var w=w||"toggle"===t;t!==(p?"hide":"show")&&m.push(e)}}if(b=m.length)for(t=c._data(a,"fxshow")||c._data(a,"fxshow",{}),("hidden"in t)&&(p=t.hidden),w&&(t.hidden=!p),p?c(a).show():f.done(function(){c(a).hide()}),f.done(function(){var Q;c._removeData(a,"fxshow");
		for(Q in k)c.style(a,Q,k[Q])}),e=0;e<b;e++){w=m[e];var G=f.createTween(w,p?t[w]:0);k[w]=t[w]||c.style(a,w);w in t||(t[w]=G.start,p&&(G.end=G.start,G.start="width"===w||"height"===w?1:0))}}],Oa={"*":[function(a,b){var d=this.createTween(a,b),e=Md.exec(b),f=d.cur(),g=+f||0,k=1,m=20;if(e){b=+e[2];var p=e[3]||(c.cssNumber[a]?"":"px");if("px"!==p&&g){g=c.css(d.elem,a,!0)||b||1;do k=k||".5",g/=k,c.style(d.elem,a,g+p);while(k!==(k=d.cur()/f)&&1!==k&&--m)}d.unit=p;d.start=g;d.end=e[1]?g+(e[1]+1)*b:b}return d}]};
	c.Animation=c.extend(ac,{tweener:function(a,b){c.isFunction(a)?(b=a,a=["*"]):a=a.split(" ");for(var d,e=0,f=a.length;e<f;e++)d=a[e],Oa[d]=Oa[d]||[],Oa[d].unshift(b)},prefilter:function(a,b){b?Va.unshift(a):Va.push(a)}});c.Tween=ha;ha.prototype={constructor:ha,init:function(a,b,d,e,f,g){this.elem=a;this.prop=d;this.easing=f||"swing";this.options=b;this.start=this.now=this.cur();this.end=e;this.unit=g||(c.cssNumber[d]?"":"px")},cur:function(){var a=ha.propHooks[this.prop];return a&&a.get?a.get(this):
			ha.propHooks._default.get(this)},run:function(a){var b,d=ha.propHooks[this.prop];this.pos=this.options.duration?b=c.easing[this.easing](a,this.options.duration*a,0,1,this.options.duration):b=a;this.now=(this.end-this.start)*b+this.start;this.options.step&&this.options.step.call(this.elem,this.now,this);d&&d.set?d.set(this):ha.propHooks._default.set(this);return this}};ha.prototype.init.prototype=ha.prototype;ha.propHooks={_default:{get:function(a){return null==a.elem[a.prop]||a.elem.style&&null!=
			a.elem.style[a.prop]?(a=c.css(a.elem,a.prop,""))&&"auto"!==a?a:0:a.elem[a.prop]},set:function(a){if(c.fx.step[a.prop])c.fx.step[a.prop](a);else a.elem.style&&(null!=a.elem.style[c.cssProps[a.prop]]||c.cssHooks[a.prop])?c.style(a.elem,a.prop,a.now+a.unit):a.elem[a.prop]=a.now}}};ha.propHooks.scrollTop=ha.propHooks.scrollLeft={set:function(a){a.elem.nodeType&&a.elem.parentNode&&(a.elem[a.prop]=a.now)}};c.each(["toggle","show","hide"],function(a,b){var d=c.fn[b];c.fn[b]=function(e,f,g){return null==
	e||"boolean"===typeof e?d.apply(this,arguments):this.animate(Wa(b,!0),e,f,g)}});c.fn.extend({fadeTo:function(a,b,d,e){return this.filter(Ma).css("opacity",0).show().end().animate({opacity:b},a,d,e)},animate:function(a,b,d,e){var f=c.isEmptyObject(a),g=c.speed(b,d,e),k=function(){var m=ac(this,c.extend({},a),g);k.finish=function(){m.stop(!0)};(f||c._data(this,"finish"))&&m.stop(!0)};k.finish=k;return f||!1===g.queue?this.each(k):this.queue(g.queue,k)},stop:function(a,b,d){var e=function(f){var g=f.stop;
			delete f.stop;g(d)};"string"!==typeof a&&(d=b,b=a,a=y);b&&!1!==a&&this.queue(a||"fx",[]);return this.each(function(){var f=!0,g=null!=a&&a+"queueHooks",k=c.timers,m=c._data(this);if(g)m[g]&&m[g].stop&&e(m[g]);else for(g in m)m[g]&&m[g].stop&&Nd.test(g)&&e(m[g]);for(g=k.length;g--;)k[g].elem!==this||null!=a&&k[g].queue!==a||(k[g].anim.stop(d),f=!1,k.splice(g,1));!f&&d||c.dequeue(this,a)})},finish:function(a){!1!==a&&(a=a||"fx");return this.each(function(){var b=c._data(this),d=b[a+"queue"];var e=b[a+
		"queueHooks"];var f=c.timers,g=d?d.length:0;b.finish=!0;c.queue(this,a,[]);e&&e.cur&&e.cur.finish&&e.cur.finish.call(this);for(e=f.length;e--;)f[e].elem===this&&f[e].queue===a&&(f[e].anim.stop(!0),f.splice(e,1));for(e=0;e<g;e++)d[e]&&d[e].finish&&d[e].finish.call(this);delete b.finish})}});c.each({slideDown:Wa("show"),slideUp:Wa("hide"),slideToggle:Wa("toggle"),fadeIn:{opacity:"show"},fadeOut:{opacity:"hide"},fadeToggle:{opacity:"toggle"}},function(a,b){c.fn[a]=function(d,e,f){return this.animate(b,
		d,e,f)}});c.speed=function(a,b,d){var e=a&&"object"===typeof a?c.extend({},a):{complete:d||!d&&b||c.isFunction(a)&&a,duration:a,easing:d&&b||b&&!c.isFunction(b)&&b};e.duration=c.fx.off?0:"number"===typeof e.duration?e.duration:e.duration in c.fx.speeds?c.fx.speeds[e.duration]:c.fx.speeds._default;if(null==e.queue||!0===e.queue)e.queue="fx";e.old=e.complete;e.complete=function(){c.isFunction(e.old)&&e.old.call(this);e.queue&&c.dequeue(this,e.queue)};return e};c.easing={linear:function(a){return a},
		swing:function(a){return.5-Math.cos(a*Math.PI)/2}};c.timers=[];c.fx=ha.prototype.init;c.fx.tick=function(){var a=c.timers,b=0;for(Ha=c.now();b<a.length;b++){var d=a[b];d()||a[b]!==d||a.splice(b--,1)}a.length||c.fx.stop();Ha=y};c.fx.timer=function(a){a()&&c.timers.push(a)&&c.fx.start()};c.fx.interval=13;c.fx.start=function(){db||(db=setInterval(c.fx.tick,c.fx.interval))};c.fx.stop=function(){clearInterval(db);db=null};c.fx.speeds={slow:600,fast:200,_default:400};c.fx.step={};c.expr&&c.expr.filters&&
	(c.expr.filters.animated=function(a){return c.grep(c.timers,function(b){return a===b.elem}).length});c.fn.offset=function(a){if(arguments.length)return a===y?this:this.each(function(g){c.offset.setOffset(this,a,g)});var b,d={top:0,left:0},e=(b=this[0])&&b.ownerDocument;if(e){var f=e.documentElement;if(!c.contains(f,b))return d;typeof b.getBoundingClientRect!==qa&&(d=b.getBoundingClientRect());b=bc(e);return{top:d.top+(b.pageYOffset||f.scrollTop)-(f.clientTop||0),left:d.left+(b.pageXOffset||f.scrollLeft)-
			(f.clientLeft||0)}}};c.offset={setOffset:function(a,b,d){var e=c.css(a,"position");"static"===e&&(a.style.position="relative");var f=c(a),g=f.offset(),k=c.css(a,"top"),m=c.css(a,"left"),p={};("absolute"===e||"fixed"===e)&&-1<c.inArray("auto",[k,m])?(m=f.position(),e=m.top,m=m.left):(e=parseFloat(k)||0,m=parseFloat(m)||0);c.isFunction(b)&&(b=b.call(a,d,g));null!=b.top&&(p.top=b.top-g.top+e);null!=b.left&&(p.left=b.left-g.left+m);"using"in b?b.using.call(a,p):f.css(p)}};c.fn.extend({position:function(){if(this[0]){var a=
			{top:0,left:0},b=this[0];if("fixed"===c.css(b,"position"))var d=b.getBoundingClientRect();else{var e=this.offsetParent();d=this.offset();c.nodeName(e[0],"html")||(a=e.offset());a.top+=c.css(e[0],"borderTopWidth",!0);a.left+=c.css(e[0],"borderLeftWidth",!0)}return{top:d.top-a.top-c.css(b,"marginTop",!0),left:d.left-a.left-c.css(b,"marginLeft",!0)}}},offsetParent:function(){return this.map(function(){for(var a=this.offsetParent||C.documentElement;a&&!c.nodeName(a,"html")&&"static"===c.css(a,"position");)a=
			a.offsetParent;return a||C.documentElement})}});c.each({scrollLeft:"pageXOffset",scrollTop:"pageYOffset"},function(a,b){var d=/Y/.test(b);c.fn[a]=function(e){return c.access(this,function(f,g,k){var m=bc(f);if(k===y)return m?b in m?m[b]:m.document.documentElement[g]:f[g];m?m.scrollTo(d?c(m).scrollLeft():k,d?k:c(m).scrollTop()):f[g]=k},a,e,arguments.length,null)}});c.each({Height:"height",Width:"width"},function(a,b){c.each({padding:"inner"+a,content:b,"":"outer"+a},function(d,e){c.fn[e]=function(f,
																																																																																																																																 g){var k=arguments.length&&(d||"boolean"!==typeof f),m=d||(!0===f||!0===g?"margin":"border");return c.access(this,function(p,q,v){return c.isWindow(p)?p.document.documentElement["client"+a]:9===p.nodeType?(q=p.documentElement,Math.max(p.body["scroll"+a],q["scroll"+a],p.body["offset"+a],q["offset"+a],q["client"+a])):v===y?c.css(p,q,m):c.style(p,q,v,m)},b,k?f:y,k,null)}})});F.jQuery=F.$=c;"function"===typeof define&&define.amd&&define.amd.jQuery&&define("jquery",[],function(){return c})})(window);
